  "DMA1": {
        "Stream0": {
            "Channel0": "SPI3_RX",
            "Channel1": "I2C1_RX",
            "Channel2": "TIM4_CH1",
            "Channel3": "I2S3_EXT_RX",
            "Channel4": "UART5_RX",
            "Channel5": "UART8_TX",
            "Channel6": ["TIM5_CH3", "TIM5_UP"],
            "Channel7": None,
        },
        "Stream1": {
            "Channel0": None,
            "Channel1": None,
            "Channel2": None,
            "Channel3": ["TIM2_UP", "TIM2_CH3"],
            "Channel4": "USART3_RX",
            "Channel5": "UART7_TX",
            "Channel6": ["TIM5_CH4", "TIM5_TRIG"],
            "Channel7": "TIM6_UP",
        },
        "Stream2": {
            "Channel0": "SPI3_RX",
            "Channel1": "TIM7_UP",
            "Channel2": "I2S3_EXT_RX",
            "Channel3": "I2C3_RX",
            "Channel4": "UART4_RX",
            "Channel5": ["TIM3_CH4", "TIM3_UP"],
            "Channel6": "TIM5_CH1",
            "Channel7": "I2C2_RX",
        },
        "Stream3": {
            "Channel0": "SPI2_RX",
            "Channel1": "TIM7_UP",
            "Channel2": "TIM4_CH2",
            "Channel3": "I2S2_EXT_RX",
            "Channel4": "USART3_TX",
            "Channel5": ["TIM3_CH1", "TIM3_TRIG"],
            "Channel6": ["TIM5_CH4", "TIM5_TRIG"],
            "Channel7": "I2C2_RX",
        },
        "Stream4": {
            "Channel0": "SPI2_TX",
            "Channel1": "I2C1_RX",
            "Channel2": "I2S2_EXT_TX",
            "Channel3": "I2C3_TX",
            "Channel4": "UART4_TX",
            "Channel5": "TIM3_CH2",
            "Channel6": "TIM5_CH2",
            "Channel7": "USART3_TX",
        },
        "Stream5": {
            "Channel0": "SPI3_TX",
            "Channel1": "I2C1_TX",
            "Channel2": "I2S3_EXT_TX",
            "Channel3": "TIM2_CH1",
            "Channel4": "USART2_RX",
            "Channel5": "UART8_RX",
            "Channel6": None,
            "Channel7": "DAC1",
        },
        "Stream6": {
            "Channel0": None,
            "Channel1": "I2C1_TX",
            "Channel2": "TIM4_UP",
            "Channel3": ["TIM2_CH2", "TIM2_UP"],
            "Channel4": "USART2_TX",
            "Channel5": "TIM3_CH3",
            "Channel6": "TIM5_UP",
            "Channel7": "DAC2",
        },
        "Stream7": {
            "Channel0": "SPI3_TX",
            "Channel1": None,
            "Channel2": "TIM4_CH3",
            "Channel3": "TIM2_CH4",
            "Channel4": "USART5_TX",
            "Channel5": None,
            "Channel6": None,
            "Channel7": "I2C2_TX",
        },
    },

    "DMA2": {
        "Stream0": {
            "Channel0": "ADC1",
            "Channel1": None,
            "Channel2": "ADC3",
            "Channel3": "SPI1_RX",
            "Channel4": "SPI4_RX",
            "Channel5": None,
            "Channel6": "TIM1_TRIG",
            "Channel7": None,
        },
        "Stream1": {
            "Channel0": None,
            "Channel1": "DCMI",
            "Channel2": "ADC3",
            "Channel3": None,
            "Channel4": None,
            "Channel5": "USART6_RX",
            "Channel6": "TIM1_CH1",
            "Channel7": "TIM8_UP",
        },
        "Stream2": {
            "Channel0": ["TIM8_CH1","TIM8_CH2","TIM8_CH3"],
            "Channel1": "ADC2",
            "Channel2": None,
            "Channel3": "SPI1_RX",
            "Channel4": "USART1_RX",
            "Channel5": "USART6_RX",
            "Channel6": "TIM1_CH2",
            "Channel7": "TIM8_CH1",
        },
        "Stream3": {
            "Channel0": None,
            "Channel1": "ADC2",
            "Channel2": "SPI5_RX",
            "Channel3": "SPI1_TX",
            "Channel4": "SDIO",
            "Channel5": "SPI4_RX",
            "Channel6": "TIM1_CH1",
            "Channel7": "TIM8_CH2",
        },
        "Stream4": {
            "Channel0": "ADC1",
            "Channel1": "SAI1_B",
            "Channel2": "SPI5_TX",
            "Channel3": None,
            "Channel4": None,
            "Channel5": "SPI4_TX",
            "Channel6": ["TIM1_CH4","TIM1_TRIG","TIM1_COM"],
            "Channel7": "TIM8_CH3",
        },
        "Stream5": {
            "Channel0": "SAI1_B",
            "Channel1": None,
            "Channel2": "CRYP_OUT",
            "Channel3": "SPI1_TX",
            "Channel4": "USART1_RX",
            "Channel5": "USART6_TX",
            "Channel6": "TIM1_UP",
            "Channel7": "SPI5_RX",
        },
        "Stream6": {
            "Channel0": ["TIM1_CH1","TIM1_CH2","TIM1_CH3"],
            "Channel1": "SPI6_RX",
            "Channel2": "CRYP_IN",
            "Channel3": None,
            "Channel4": "SDIO",
            "Channel5": "USART6_TX",
            "Channel6": "TIM1_CH3",
            "Channel7": "SPI5_TX",
        },
        "Stream7": {
            "Channel0": None,
            "Channel1": "DCMI",
            "Channel2": "HASH_IN",
            "Channel3": None,
            "Channel4": "USART1_TX",
            "Channel5": None,
            "Channel6": None,
            "Channel7": ["TIM8_CH4","TIM8_TRIG","TIM8_COM"],
        },
    }
}