Erika3 Manual: inc/ee_kernel_types.h File Reference
ee_kernel_types.h File Reference
OSEK Kernel Internal Types.
#include "ee_cfg.h"
#include "ee_api_types.h"
#include "ee_oo_api_extension.h"
#include "ee_hal_internal_types.h"
#include "ee_scheduler_types.h"
Data Structures
struct OsEE_MCB
Mutual exclusion control block.
struct OsEE_MDB_tag
Mutual exclusion descriptor block.
struct OsEE_TCB
The Task Control Block.
struct OsEE_TDB_tag
The Task Descriptor Block.
struct OsEE_TW
This is the generic definition of a task wrapper.
struct OsEE_CounterCB
Counter Control Block.
struct OsEE_CounterDB
Counter descriptor block.
struct OsEE_action_param
Parameters of an Alarm/Schedule Table expiration (function callback, task, event mask, and counter)
struct OsEE_action
Notification data structure for Alarms and Schedule Tables.
struct OsEE_st_exipiry_point_tag
Structures that hold the information related to an expiry point.
struct OsEE_AlarmCB_tag
Alarm Control Block.
struct OsEE_AlarmDB_tag
Alarm descriptor block.
struct OsEE_SchedTabCB_tag
Data structure to store RAM informations needed by schedule tables.
struct OsEE_SchedTabDB_tag
This is the data structure used to describe the constant part of a schedule table.
struct OsEE_TriggerCB
The Trigger Countrol Block is the element in the trigger queue that records when the next trigger is going to expire, and what is its status (see OsEE_trigger_status).
struct OsEE_TriggerDB_tag
Trigger Descriptor Block is the elemnt containing the information of Alarms and Schedule Tables.
struct OsEE_CCB
This is the Core Control Block.
struct OsEE_CDB
This is the Core Descriptor Block.
struct OsEE_KCB
This is the Kernel Control Block.
struct OsEE_KDB
This is the Kernel descriptor Block.
Macros
#define OSEE_HAS_CONTEXT
This architecture requires the saving of a context in the CCB (Core Control Block)
#define OSEE_MAX_BYTE ((OsEE_byte)-1)
Byte: the maximum value for a byte.
#define OSEE_COUNTER_TRIGGER_TYPES
If the application contains both Alarms and Schedule Tables, then the Trigger queue OsEE_TriggerQ will distinguis among the two types of objects.
Typedefs
typedef void(* OS_APPL_DATA) (void)
Kernel Callback.
typedef uint8_t TYPEDEF OsEE_byte
Byte: the smallest type instantiable.
typedef struct OsEE_MDB_tag OsEE_MDB
Mutual exclusion descriptor block.
typedef OsEE_MCB OsEE_ResourceCB
The Resource Control Block.
typedef OsEE_MDB OsEE_ResourceDB
The Resource Descriptor Block.
typedef OsEE_MCB OsEE_SpinlockCB
The Spin Lock Control Block.
typedef OsEE_MDB OsEE_SpinlockDB
The Spin Lock Descriptor Block.
typedef struct OsEE_TDB_tag OsEE_TDB
The Task Descriptor Block.
typedef struct OsEE_TriggerDB_tag const TYPEDEF *OS_APPL_DATA OsEE_TriggerQ
This is the type used for the trigger queue.
typedef OsEE_st_synch_strategy SynchStrategyType
to have a more harmonized type name with other OSEK type names.
typedef struct OsEE_st_exipiry_point_tag OsEE_st_exipiry_point
Structures that hold the information related to an expiry point.
typedef struct OsEE_AlarmCB_tag OsEE_AlarmCB
Alarm Control Block.
typedef struct OsEE_AlarmDB_tag OsEE_AlarmDB
Alarm descriptor block.
typedef struct OsEE_SchedTabCB_tag OsEE_SchedTabCB
Data structure to store RAM informations needed by schedule tables.
typedef struct OsEE_SchedTabDB_tag OsEE_SchedTabDB
This is the data structure used to describe the constant part of a schedule table.
typedef struct OsEE_TriggerDB_tag OsEE_TriggerDB
Trigger Descriptor Block is the elemnt containing the information of Alarms and Schedule Tables.
Enumerations
enum OsEE_os_context {
OSEE_KERNEL_CTX , OSEE_IDLE_CTX , OSEE_TASK_CTX , OSEE_TASK_ISR2_CTX ,
OSEE_ERRORHOOK_CTX , OSEE_PROTECTIONHOOK_CTX , OSEE_PRETASKHOOK_CTX , OSEE_POSTTASKHOOK_CTX ,
OSEE_STARTUPHOOK_CTX , OSEE_SHUTDOWNHOOK_CTX , OSEE_ALARMCALLBACK_CTX
}
OS-Application contexts enum used to implement Autosar OS OS_SWS_088 requirement.
enum OsEE_kernel_status { OSEE_KERNEL_INITIALIZED , OSEE_KERNEL_STARTING , OSEE_KERNEL_STARTED , OSEE_KERNEL_SHUTDOWN }
This enumerate controls the status of the kernel over the application execution.
enum OsEE_m_type { OSEE_M_RESOURCE , OSEE_M_SPINLOCK }
Mutual Exclusion type.
enum OsEE_action_type { OSEE_ACTION_TASK , OSEE_ACTION_EVENT , OSEE_ACTION_COUNTER , OSEE_ACTION_CALLBACK }
Possible types of notifications for Alarms and Schedule Tables.
enum OsEE_st_synch_strategy { OSEE_SCHEDTABLE_SYNC_NONE , OSEE_SCHEDTABLE_SYNC_IMPLICIT , OSEE_SCHEDTABLE_SYNC_EXPLICIT }
Schedule Table Synchronization strategies symbols.
enum OsEE_trigger_status {
OSEE_TRIGGER_INACTIVE , OSEE_TRIGGER_CANCELED , OSEE_TRIGGER_ACTIVE , OSEE_TRIGGER_EXPIRED ,
OSEE_TRIGGER_REENABLED
}
This is the trigger status enumerate.
Functions
void OS_CODE osEE_change_context_from_isr2_end (OsEE_TDB *OS_APPL_CONST p_from, OsEE_TDB *OS_APPL_CONST p_to)
Handles the ISR2 termination.
void OS_CODE osEE_change_context_from_task_end (OsEE_TDB *OS_APPL_CONST p_from, OsEE_TDB *OS_APPL_CONST p_to)
Handles the Task termination.
void OS_CODE osEE_idle_hook_wrapper (void)
Task Body of the Idle Task.
Detailed Description
This files contains all internal types and symbols for OSEK Kernel support in Erika Enterprise.
Author
Errico Guidieri
Date
2016
Macro Definition Documentation
OSEE_COUNTER_TRIGGER_TYPES
#define OSEE_COUNTER_TRIGGER_TYPES
If there is only one kind of object, then we use an optimized implementation.
OSEE_MAX_BYTE
#define OSEE_MAX_BYTE ((OsEE_byte)-1)
Byte: the maximum value for a byte
Typedef Documentation
OsEE_AlarmCB
typedef struct OsEE_AlarmCB_tag OsEE_AlarmCB
It stores the RAM information about the alarm. This data structure is present only if both Alarms and Schedule Tables are present in the application. Otherwise, the content of this data structure is integrated inside the trigger.
OsEE_AlarmDB
typedef struct OsEE_AlarmDB_tag OsEE_AlarmDB
It stores the Flash information about an alarm. This data structure is present only if both Alarms and Schedule Tables are present in the application. Otherwise, the content of this data structure is integrated inside the trigger.
OsEE_MDB
typedef struct OsEE_MDB_tag OsEE_MDB
The descriptor block tracks the specific mutual exclusion object, which can be either a Resource or a Spin Lock. They are handled together because they have to be released in LIFO order [SWS_Os_00801].
OsEE_TDB
typedef struct OsEE_TDB_tag OsEE_TDB
It stores all the information related to the task that is configured statically, such as: priority, task type, task body pointer, maximum number of activations, core id, ...
OsEE_TriggerDB
typedef struct OsEE_TriggerDB_tag OsEE_TriggerDB
If both Alarms and Schedule Tables are present in the Application, the struct has two pointers to the Alarm and to the Schedule Table Descriptor blocks. Only one of them is different from NULL (this is implicitly the type of the trigger). If only Alarms or only Schedule Tables are present, the struct contains the fields of the descriptor block, saving one indirection.
OsEE_TriggerQ
typedef struct OsEE_TriggerDB_tag const TYPEDEF* OS_APPL_DATA OsEE_TriggerQ
The trigger queue represents a queue of expiry points which could come either from Alarms or from Schedule Tables. If both (Alarms and Schedule Tables) are present inside an application, then the trigger queue has two pointers, one to the Alarm data, one to the Schedule Table data, and only one of them will be set, implicitly stating the type of object. If only one kind of object is present in the Application, then we avoid the indirection and the specific item data is put inside the OsEE_TriggerCB and inside the OsEE_TriggerDB.
Also note that the Trigger Queue is a Linked List, but in theory we could implement any priority queue data structure (Heap for example)
Enumeration Type Documentation
OsEE_kernel_status
enum OsEE_kernel_status
Enumerator
OSEE_KERNEL_INITIALIZED
before OS initialization
OSEE_KERNEL_STARTING
before the call to StartupHook() and autostart
OSEE_KERNEL_STARTED
after the call to StartupHook() and autostart
OSEE_KERNEL_SHUTDOWN
ShutdownOS() called.
OsEE_m_type
enum OsEE_m_type
The Mutual exclusion type is only present if the application uses both Resources and Spin locks, and is used to mark the type of the specific object (either a Resource or a Spin Lock). The idea is that when the application only has one type of these objects (either only Resources or only Spin Locks), the system is optimized reducing the overhead of the additional indirection.
OsEE_os_context
enum OsEE_os_context
Used in addition to handle not recursive calls at ErrorHook
OsEE_st_synch_strategy
enum OsEE_st_synch_strategy
Enumerator
OSEE_SCHEDTABLE_SYNC_NONE
No support for synchronization.
(default)
OSEE_SCHEDTABLE_SYNC_IMPLICIT
The counter driving the schedule table is the counter with which synchronization is required.
OSEE_SCHEDTABLE_SYNC_EXPLICIT
The schedule table is driven by an OS counter but processing needs to be synchronized with a different counter which is not an OS counter object.
Specification of Operating System
OsEE_trigger_status
enum OsEE_trigger_status
The trigger statuses have been made to consistently handle race conditions on the update of Alarms and Schedule Tables.
In particular, in the multicore case we have a potential race condition due to the following:
the handling of the trigger data structure is done in mutual exclusion using a spin lock.
the spinlock is released during the handling of the notifications. This is done because the time spent in handling notifications may be long (e.g., a Schedule Table activating a number of tasks at an expiry point.
when a core is handling the notifications at an expiry point related to an Alarm (Schedule Table), with the spin lock unlocked, a CancelAlarm() (StopScheduleTable()) could be issued by another core on the same Alarm (Schedule Table). Once canceled (stopped), the Alarm (Schedule Table) could be restarted again.
Therefore, the status transitions of a trigger will be the following:
OSEE_TRIGGER_INACTIVE: Initial status, trigger inactive
OSEE_TRIGGER_ACTIVE: Alarm or Schedule Table started
OSEE_TRIGGER_EXPIRED: The trigger fired. The status is changed to expired before leaving the critical section.
OSEE_TRIGGER_CANCELED: The status is set to canceled if while the trigger is expired and the spin lock released a CancelAlarm() or StopScheduleTable() arrives from another core. At the end of the notification handling the status will be set back to OSEE_TRIGGER_INACTIVE
OSEE_TRIGGER_REENABLED: The status is set to reenabled if a canceled Alarm or ScheduleTable is reenabled while a core is still handling the actions. At the end of the notification handling the status will be set to OSEE_TRIGGER_ACTIVE with the new start time.
Function Documentation
osEE_change_context_from_isr2_end()
void OS_CODE osEE_change_context_from_isr2_end (OsEE_TDB *OS_APPL_CONST p_from, OsEE_TDB *OS_APPL_CONST p_to) extern
This function handles the context change at ISR2 termination.
This is an internal function of the ERIKA3 Hardware Abstraction Layer, called by the Kernel, provided by each porting in an architecture dependent way. The typical implementation acknowledges the interrupt controller and then calls afterwards the osEE_change_context_from_task_end.
Note: this include file is not the "best" place to place this function. ... but is a good point because it is visible to teh HAL implementation. Likely this declaration will move soon or later to another include file.
Parameters
[in] p_from Current ISR2 in execution
[in] p_to New task to execute
References AUTOMATIC, OS_APPL_CONST, OS_CODE, osEE_change_context_from_isr2_end(), and P2VAR.
Referenced by osEE_change_context_from_isr2_end().
osEE_change_context_from_task_end()
void OS_CODE osEE_change_context_from_task_end (OsEE_TDB *OS_APPL_CONST p_from, OsEE_TDB *OS_APPL_CONST p_to) extern
This function handles the context change at Task termination.
This is an internal function of the ERIKA3 Hardware Abstraction Layer, called by the Kernel, provided by each porting in an architecture dependent way.
Note: this include file is not the "best" place to place this function. ... but is a good point because it is visible to teh HAL implementation. Likely this declaration will move soon or later to another include file.
Parameters
[in] p_from Current ISR2 in execution
[in] p_to New task to execute
References AUTOMATIC, FUNC, OS_APPL_CONST, OS_CODE, osEE_change_context_from_task_end(), and P2VAR.
Referenced by osEE_change_context_from_task_end().
osEE_idle_hook_wrapper()
void OS_CODE osEE_idle_hook_wrapper (void) extern
This is the Task Body of the Idle task.
References osEE_idle_hook_wrapper().
Referenced by osEE_idle_hook_wrapper().