Erika3 Manual: inc/ee_scheduler_types.h File Reference
ee_scheduler_types.h File Reference
Contains the types for different scheduler data structures.
#include "ee_cfg.h"
#include "ee_utils.h"
#include "ee_compiler.h"
#include "ee_platform_types.h"
#include "ee_api_types.h"
Data Structures
struct OsEE_SN_tag
Scheduler node data structure.
struct OsEE_sem_tag
Semaphore Data structure.
Macros
#define OSEE_RQ_LL
in case it is not defined the OSEE_RQ_MULTIQUEUE, define the OSEE_RQ_LL, which is the linked list implementation.
Typedefs
typedef struct OsEE_SN_tag OsEE_SN
Scheduler node data structure.
typedef OsEE_SN * OsEE_RQ
When implemented with a linked list, a ready queue is a list of scheduler nodes.
typedef struct OsEE_sem_tag OsEE_sem
Semaphore Data structure.
typedef struct OsEE_sem_tag SemType
A semaphore data structure with a OSEK/VDX naming convention flavour.
Functions
OSEE_STATIC_INLINE OsEE_SN *OS_APPL_DATA OS_CODE osEE_sn_alloc (OsEE_SN **OS_APPL_DATA pp_first)
Removes the first node from a node list.
OSEE_STATIC_INLINE void OS_CODE osEE_sn_release (OsEE_SN **OS_APPL_DATA pp_first, OsEE_SN *OS_APPL_DATA p_to_free)
Inserts a node as the first of a list.
OsEE_bool OS_CODE osEE_sn_priority_insert (OsEE_SN **OS_APPL_DATA pp_first, OsEE_SN *OS_APPL_DATA p_sn_new, CONST(OsEE_bool,) as_ready)
Ordered insertion in a queue.
Detailed Description
Author
Errico Guidieri
Date
2016
Typedef Documentation
OsEE_sem
typedef struct OsEE_sem_tag OsEE_sem
A counter, a blocked queue, and a spinlock in case of multicores.
OsEE_SN
typedef struct OsEE_SN_tag OsEE_SN
The Scheduler queues are composed by lists of nodes.
Function Documentation
osEE_sn_alloc()
OSEE_STATIC_INLINE OsEE_SN *OS_APPL_DATA OS_CODE osEE_sn_alloc (OsEE_SN **OS_APPL_DATA pp_first)
Removes the first node in a task list. Typically called on the free node list.
Parameters
[in,out] pp_first Pointer to (the pointer to the first node of a queue)
Returns
Returns a pointer to a node.
References AUTOMATIC, OS_APPL_DATA, osEE_sn_alloc(), and P2VAR.
Referenced by osEE_sn_alloc().
osEE_sn_priority_insert()
OsEE_bool OS_CODE osEE_sn_priority_insert (OsEE_SN **OS_APPL_DATA pp_first, OsEE_SN *OS_APPL_DATA p_sn_new, CONST(OsEE_bool,) as_ready)
This functon inserts a task inside a task queue, following the order of the task.
Parameters
[in,out] pp_first Pointer to (the pointer to the first node of a queue)
[in] p_sn_new Node to be inserted in the list following the priority of its task
[in] as_ready If OSEE_TRUE, use the ready_priority and not the current priority to queue the task. The usage of the ready priority is useful when doing global schedulng. In AUTOSAR conformance classes, onlt the current priority is used.
Returns
The function returns OSEE_TRUE if the head pp_first changed.
References AUTOMATIC, CONST, OS_APPL_DATA, osEE_sn_priority_insert(), P2VAR, and TYPEDEF.
Referenced by osEE_sn_priority_insert().
osEE_sn_release()
OSEE_STATIC_INLINE void OS_CODE osEE_sn_release (OsEE_SN **OS_APPL_DATA pp_first, OsEE_SN *OS_APPL_DATA p_to_free)
Inserts a node as the first of a list. Typically called on the free node list to "release" a scheduler node.
Parameters
[in,out] pp_first Pointer to (the pointer to the first node of a queue)
[in,out] p_to_free Node to be inserted in the list
References AUTOMATIC, OS_APPL_DATA, osEE_sn_release(), and P2VAR.
Referenced by osEE_sn_release().