Erika3 Manual: Application modes, Startup and Shutdown primitives
Application modes, Startup and Shutdown primitives
ERIKA3 supports the specification of a set of Application Modes.
Macros
#define INVALID_APPMODE ((AppModeType)-1)
Value for invalid application modes.
#define OSDEFAULTAPPMODE ((AppModeType)0U)
Default Application Mode.
#define DONOTCARE ((AppModeType)-1)
Do Not Care Application Mode.
Typedefs
typedef OSEE_APPMODE_TYPE AppModeType
Type used for application modes.
Functions
StatusType OS_CODE StartOS (AppModeType Mode)
Operating system startup routine.
StatusType OS_CODE ShutdownOS (StatusType Error)
Abort the overall system.
AppModeType OS_CODE GetActiveApplicationMode (void)
Reads the current application mode.
Detailed Description
Application modes are startup configurations that are used to configure the running application for a certain mode of operation. Examples of Application Modes are for example Normal execution, Flash Programming, Debug Mode, and so on.
The main idea is that the CPU startup code somehow discovers the current Application mode (Typical ways to discover Application Modes are for example the usage of dip switches on the device board). Once done that, the application mode is passed to StartOS(), that sets the application mode for this run. Once the system is started, the application mode value can be read using a call to GetActiveApplicationMode().
Application modes are listed inside the OIL configuration file. There always exist at least one application mode called OSDEFAULTAPPMODE. Once set at startup into StartOS(), the Application mode cannot be changed.
Application modes are also useful to autostart tasks and alarms following a call to StartOS(). Tasks and alarms autostart features must be specified inside the OIL configuration file.
Application modes should not be used to map application states that may vary during the application execution.
The primitive ShutdownOS() is used to prepare the system for system shutdown. The function simply calls ShutdownHook() and then it starts a forever loop waiting for an hardware reset.
On multicore systems, the StartOS() and ShutdownOS() are implemented respecting the AUTOSAR specifications, in particular related to the usage of barriers to synchronize the cores startup/shutdown.
Macro Definition Documentation
DONOTCARE
#define DONOTCARE ((AppModeType)-1)
Do Not Care Application Mode. Inherits the startup mode from other cores.
Reference: AUTOSAR OS - [SWS_Os_91007]
INVALID_APPMODE
#define INVALID_APPMODE ((AppModeType)-1)
Value for invalid application modes. No application mode will have this value.
OSDEFAULTAPPMODE
#define OSDEFAULTAPPMODE ((AppModeType)0U)
Default Application Mode. Always a valid parameter for StartOS()
Reference: OSEK OS - ISO 17356-3 - 13.8.3
Typedef Documentation
AppModeType
typedef OSEE_APPMODE_TYPE AppModeType
This is the type that stores Application modes. It is an integer value.
Function Documentation
GetActiveApplicationMode()
AppModeType OS_CODE GetActiveApplicationMode (void)
The function returns the current Application Mode, that has been set up by StartOS() at system startup.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.8.2.1
Returns
The function returns the current application mode.
References FUNC, GetActiveApplicationMode(), and OS_CODE.
Referenced by GetActiveApplicationMode().
ShutdownOS()
StatusType OS_CODE ShutdownOS (StatusType Error)
The user can call this system service to abort the overall system (e.g. emergency off).
If a ShutdownHook() is configured the hook routine ShutdownHook() is always called (with Error as argument) before shutting down the operating system.
The Operating system shutdown is currently implemented as a forever loop with interrupt disabled.
In case of multicore devices, the ShutdownHook takes care of multicore synchronization and multicore shutdown as specified by the AUTOSAR OS standard.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.8.2.3
Parameters
[in] Error The identifier of the error which occurred.
Returns
The function does not return.
References AUTOMATIC, FUNC, OS_CODE, ShutdownOS(), and VAR.
Referenced by ShutdownOS().
StartOS()
StatusType OS_CODE StartOS (AppModeType Mode)
The user can call this system service to start the operating system in a specific Application mode. Only allowed outside of the operating system, at startup. The function calls in order the StartupHook(), then it activates the tasks and set the alarms AUTOSTART set as TRUE inside the OIL configuration file. After that, the system is rescheduled and the highest priority ready task is executed.
The StartOS() primitive by default never returns to the caller.
If specified in the OIL file, the idle loop hook will be called inside the StartOS().
On multicore systems, the StartOS() have to be called by each core, as specified by the AUTOSAR OS standard.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.8.2.2
Parameters
[in] Mode The startup application mode.
Returns
The function returns a StatusType.
E_OK (Extended) No error.
E_OS_SYS_INIT (Extended) Error during initialization.
References AUTOMATIC, FUNC, OS_CODE, StartOS(), and VAR.
Referenced by StartOS().