Erika3 Manual: Event Primitives
Event Primitives
The Event Primitives are related to event handling in Extended Tasks.
Macros
#define DeclareEvent(Event)
Event Declaration.
Typedefs
typedef OSEE_EVENT_MASK_TYPE EventMaskType
Type representing the value of an event mask.
typedef EventMaskType TYPEDEF *OS_APPL_DATA EventMaskRefType
Pointer to an event mask.
Functions
StatusType OS_CODE WaitEvent (EventMaskType Mask)
The calling task waits for one of the events in the Mask.
StatusType OS_CODE SetEvent (TaskType TaskID, EventMaskType Mask)
Set an event mask on an extended task.
StatusType OS_CODE GetEvent (TaskType TaskID, EventMaskRefType Event)
returns the current event mask of an extended task.
StatusType OS_CODE ClearEvent (EventMaskType Mask)
Clears the events of the calling task.
Detailed Description
Events represents a technique used by ERIKA3 to implement synchronization primitives. Events are assigned to tasks. Tasks with events assigned to are called Extended tasks. Tasks without events assigned to are called Basic Tasks.
Extended tasks are supported only in the ECC1 and ECC2 conformance classes. To assign an event to a task, the event have to be listed inside the task declaration in the OIL configuration file.
Events are implemented as bits in a bit mask. Each task in the system is associated to a bit mask, which is typically as large as a CPU data register. The bit mask is initialized to 0 at system startup.
The status of an extended task event mask can be read by tasks and ISRs using the GetEvent() primitive. Events can also be set from tasks or ISRs using the SetEvent() primitive (more than one event can be set with a single call to SetEvent()).
An extended task can wait for one ore more events from an event mask to be set using the WaitEvent() primitive. An extended task needs then to explicitly clear an event calling the ClearEvent() primitive.
Calls to WaitEvent() may provoke the task to block. For that reason, extended tasks must have a private stack assigned to them.
Macro Definition Documentation
DeclareEvent
#define DeclareEvent (Event)
Declares an event used by Extended Tasks.
This declaration is currently not mandatory because event identifiers are all declared within the code generated by RT-Druid.
Reference: OSEK OS - ISO 17356-3 - 13.6.2.1
Parameters
[in] Event The event to be declared.
Returns
void
Typedef Documentation
EventMaskRefType
typedef EventMaskType TYPEDEF* OS_APPL_DATA EventMaskRefType
This is a pointer to an EventMaskType. it is used as an [out] parametre to some of the OSEK primitives.
EventMaskType
typedef OSEE_EVENT_MASK_TYPE EventMaskType
This type represents the value of an event mask. Please note that each Extended task has a private mask of events reserved for the usage with the event primitives. The number of events available depend on the architecture and it is typically the size of a microcontroller word.
Function Documentation
ClearEvent()
StatusType OS_CODE ClearEvent (EventMaskType Mask)
ClearEvent() clears the events Mask of the calling task.
This system call is restricted to extended tasks which own the event.
Conformance Classes: ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.6.3.2
Parameters
[in] Mask Event Mask to be cleared.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ACCESS (Extended) The service has been invoked by a non-extended task.
E_OS_CALLEVEL (Extended) The service has been invoked at the interrupt level.
References AUTOMATIC, ClearEvent(), OS_CODE, and VAR.
Referenced by ClearEvent().
GetEvent()
StatusType OS_CODE GetEvent (TaskType TaskID, EventMaskRefType Event)
This primitive returns the current state of all event bits of the task TaskID. The service may be called from interrupt service routines, task level and some hook routines. The current status of the event mask of task TaskID is copied to Event. The referenced task shall be an extended task.
Conformance Classes: ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.6.3.3
Parameters
[in] TaskID The extended task whose mask is to be returned.
[out] Event The mask of the extended task.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ID (Extended) Reference TaskID is invalid.
E_OS_ACCESS (Extended) Task TaskID is not an extended task.
E_OS_STATE (Extended) Events can not be read as the referenced task is in the SUSPENDED state.
References AUTOMATIC, FUNC, GetEvent(), OS_CODE, and VAR.
Referenced by GetEvent().
SetEvent()
StatusType OS_CODE SetEvent (TaskType TaskID, EventMaskType Mask)
The events of task TaskID are set according to the event mask Mask. The call to SetEvent() may cause TaskID to wakeup from a WaitEvent() primitive. Any events not set in the event mask remain unchanged. The service may be called from an interrupt service routine and from the task level, but not from hook routines.
The function can be called from the idle hook.
Conformance Classes: ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.6.3.1
Parameters
[in] TaskID The extended task on which we will set the event mask.
[in] Mask The mask of the extended task.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ID (Extended) Reference TaskID is invalid.
E_OS_ACCESS (Extended) Task TaskID is not an extended task.
E_OS_STATE (Extended) Events can not be set as the referenced task is in the SUSPENDED state.
References AUTOMATIC, FUNC, OS_CODE, SetEvent(), and VAR.
Referenced by SetEvent().
WaitEvent()
StatusType OS_CODE WaitEvent (EventMaskType Mask)
The calling task blocks if none of the events specified in Mask are set.
If the calling task blocks, the system is reschedule, and the Internal resource of the task is released. This service shall only be called from the extended task owning the events.
Conformance Classes: ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.6.3.4
Parameters
[in] Mask Mask of the event waited for.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ACCESS (Extended) Task TaskID is not an extended task.
E_OS_RESOURCE (Extended) Calling task occupies resources.
E_OS_CALLLEVEL (Extended) Call at interrupt level.
References AUTOMATIC, FUNC, OS_CODE, VAR, and WaitEvent().
Referenced by WaitEvent().