#ifndef __PERIPHERALS_H__
#define __PERIPHERALS_H__

#include "stm32u5xx_hal.h"

#define UART_INSTANCE USART1
#define UART_BAUDRATE 115200
#define UART_RCC_PERIPHCLK RCC_PERIPHCLK_USART1
#define __HAL_RCC_GPIO_CLK_ENABLE  __HAL_RCC_GPIOA_CLK_ENABLE
#define __HAL_RCC_UART_CLK_ENABLE  __HAL_RCC_USART1_CLK_ENABLE
#define __HAL_RCC_UART_CLK_DISABLE __HAL_RCC_USART1_CLK_DISABLE
#define UART_TX_GPIO_PIN GPIO_PIN_9
#define UART_RX_GPIO_PIN GPIO_PIN_10
#define UART_GPIO_PORT GPIOA
#define UART_GPIO_MODE GPIO_MODE_AF_PP
#define UART_GPIO_SPEED GPIO_SPEED_FREQ_VERY_HIGH
#define UART_GPIO_ALTERNATE GPIO_AF7_USART1

void UART_Init(void);

#endif