# ###*B*###
#
# ERIKA Enterprise - a tiny RTOS for small microcontrollers
# 
# Copyright (C) 2002-2018 Evidence Srl
# 
# This file is part of ERIKA Enterprise.
# 
# See LICENSE file.
#
# ###*E*###

############################################################################
#
# This file is generated by RT-Druid.
# Please do not modify it.
#
############################################################################

############################################################################
#
# User options
#
############################################################################
OS_EE_OPT += OS_EE_APPL_BUILD_DEBUG
OS_EE_OPT += OS_EE_BUILD_DEBUG


############################################################################
#
# Automatic options
#
############################################################################
OS_EE_OPT += OSEE_HAS_IDLEHOOK
OS_EE_OPT += OSEE_HAS_STARTUPHOOK
OS_EE_OPT += OSEE_MULTI_STACK
OS_EE_OPT += OSEE_OC_BCC1
OS_EE_OPT += OSEE_SINGLE_ACTIVATION
OS_EE_OPT += OSEE_SYS_STACK_SIZE (0x400U)
OS_EE_OPT += OSEE_SYS_STACK_SIZE_ASM 0x400
OS_EE_OPT += OS_EE_ARCH_CORTEX_M
OS_EE_OPT += OS_EE_ARCH_CORTEX_M_M4
OS_EE_OPT += OS_EE_ARCH_CORTEX_M_STM32F4
OS_EE_OPT += OS_EE_ARCH_CORTEX_M_STM32F407xx
OS_EE_OPT += OS_EE_ARCH_CORTEX_M_STM32F4_DISCOVERY
OS_EE_OPT += OS_EE_GCC
OS_EE_OPT += OS_EE_GCC_invalid
OS_EE_OPT += OS_EE_KERNEL_OSEK
OS_EE_OPT += OS_EE_RTD_BUILD_ENV_NATIVE
OS_EE_OPT += OS_EE_RTD_DISABLE_OS_EE_OPT_DEFINES

OS_EE_LIB_OPT += OS_EE_LIB_STM32F4_DISCOVERY
OS_EE_LIB_OPT += OS_EE_LIB_STM32_CUBE_F4
OS_EE_LIB_OPT += OS_EE_LIB_STM32_CUBE_F4_1_18_0
OS_EE_LIB_OPT += OS_EE_LIB_STM32_CUBE_F4_SA

export OS_EE_LIB_OPT




############################################################################
#
# Path check and conversion
#
############################################################################
-include $(OS_EE_BASE_DIR)/mk/ee_path_helper.mk
-include $(ERIKA_FILES)/mk/ee_path_helper.mk


############################################################################
#
# STM32CubeF4 Firmware Package path
#
############################################################################
$(eval $(call check_and_set_linux_compiler_path,STM32_CUBE_F4_FILES,/home/araujoj20/eclipse-SDK-4.8-linux-gtk-x86_64/stm32cubef4_v1-25-0/STM32Cube_FW_F4_V1.25.0))

############################################################################
#
# Compiler path
#
############################################################################
$(eval $(call check_and_set_linux_compiler_path,ARM_TOOLS,/home/araujoj20/eclipse-SDK-4.8-linux-gtk-x86_64/gcc-arm-none-eabi-7-2018-q2-update))



############################################################################
#
# Init MCU for CORTEX_M (STM32F4)
#
############################################################################
OS_EE_CORTEX_M_MCU := STM32F407xx
export OS_EE_CORTEX_M_MCU


############################################################################
#
# Flags
#
############################################################################
CFLAGS  +=
export CFLAGS

ASFLAGS +=
export ASFLAGS

LDFLAGS +=
export LDFLAGS

LDDEPS  +=
export LDDEPS

LIBS    +=
export LIBS


############################################################################
#
# Sources
#
############################################################################
OS_EE_CFG_SRCS +=
OS_EE_CFG_SRCS += ee_oscfg.c
export OS_EE_CFG_SRCS


############################################################################
#
# End
#
############################################################################

