#ifndef __DMA_H__
#define __DMA_H__

#include "stm32l5xx_hal.h"

extern DMA_HandleTypeDef hdma;

#define __HAL_RCC_DMAMUX_CLK_ENABLE __HAL_RCC_DMAMUX1_CLK_ENABLE
#define __HAL_RCC_DMA_CLK_ENABLE __HAL_RCC_DMA1_CLK_ENABLE
#define DMA_INSTANCE DMA1_Channel1
#define DMA_DIRECTION  DMA_MEMORY_TO_MEMORY
#define DMA_PERIPH_INC DMA_PINC_DISABLE
#define DMA_MEM_INC DMA_MINC_DISABLE
#define DMA_PERIPH_DATA_ALIGNMENT DMA_PDATAALIGN_BYTE
#define DMA_MEM_DATA_ALIGNMENT DMA_MDATAALIGN_BYTE
#define DMA_MODE DMA_NORMAL
#define DMA_PRIORITY DMA_PRIORITY_LOW
#define DMA_CHANNEL_ATTR DMA_CHANNEL_NPRIV
#define DMA_IRQ DMA1_Channel1_IRQn

void DMA_Init(void);

#endif