#ifndef __UART_H__
#define __UART_H__

#include "stm32l5xx_hal.h"

extern UART_HandleTypeDef huart;
#define UART_INSTANCE LPUART1
#define UART_BAUDRATE 115200
#define UART_RCC_PERIPHCLK RCC_PERIPHCLK_LPUART1
#define __HAL_RCC_GPIO_CLK_ENABLE  __HAL_RCC_GPIOG_CLK_ENABLE
#define __HAL_RCC_UART_CLK_ENABLE  __HAL_RCC_LPUART1_CLK_ENABLE
#define __HAL_RCC_UART_CLK_DISABLE __HAL_RCC_LPUART1_CLK_DISABLE
#define UART_TX_GPIO_PIN GPIO_PIN_7
#define UART_RX_GPIO_PIN GPIO_PIN_8
#define UART_GPIO_PORT GPIOG
#define UART_GPIO_MODE GPIO_MODE_AF_PP
#define UART_GPIO_SPEED GPIO_SPEED_FREQ_VERY_HIGH
#define UART_GPIO_ALTERNATE GPIO_AF8_LPUART1

void UART_Init(void);

#endif