Erika3 Manual: Schedule Tables
Schedule Tables
Schedule Tables are an extension of the Alarm concept, allowing the definition of periodic tables with multiple expiry points.
Functions
StatusType OS_CODE StartScheduleTableRel (ScheduleTableType ScheduleTableID, TickType Offset)
Starts a Schedule Table with a relative offset.
StatusType OS_CODE StartScheduleTableAbs (ScheduleTableType ScheduleTableID, TickType Start)
Starts a Schedule Table at an absolute counter value.
StatusType OS_CODE StopScheduleTable (ScheduleTableType ScheduleTableID)
Stops a Schedule Table.
StatusType OS_CODE GetScheduleTableStatus (ScheduleTableType ScheduleTableID, ScheduleTableStatusRefType ScheduleStatus)
Queries the state of a schedule table.
StatusType OS_CODE NextScheduleTable (ScheduleTableType ScheduleTableID_From, ScheduleTableType ScheduleTableID_To)
Switches to another Schedule table.
StatusType OS_CODE SyncScheduleTable (ScheduleTableType ScheduleTableID, TickType Value)
Starts synchronization of a Schedule Table.
Detailed Description
ERIKA3 supports Schedule Tables as specified by the AUTOSAR OS Specification.
Schedule Tables provide an operating system object that encapsulates a set of "expiry points" organized in the form of a table. The table can be set to be repeated periodically.
The Schedule Tables can be seen as an extension of the alarm concept, in the sense that a Schedule Table includes inside its configuration multiple notifications that otherwise needed a separate alarm each.
The Schedule Table also solves the need of atomically changing the set of expiry points, by providing the possibility to change, with a single primitive, the current running Schedule Table.
The Schedule Table provides the possibility of synchronization with an external time source. This feature has not been implemented yet in ERIKA3.
Function Documentation
GetScheduleTableStatus()
StatusType OS_CODE GetScheduleTableStatus (ScheduleTableType ScheduleTableID, ScheduleTableStatusRefType ScheduleStatus)
This service queries the state of a schedule table (also with respect to synchronization).
Sync/Async: Synchronous
Reentrancy: Reentrant
Reference: AUTOSAR OS 8.4.16 GetScheduleTableStatus [SWS_Os_00227] (SRS_Os_11002)
Parameters
[in] ScheduleTableID Schedule table for which status is requested.
[out] ScheduleStatus Reference to ScheduleTableStatusType.
Returns
The function returns a StatusType.
E_OK No Error
E_OS_ID (Extended) Invalid ScheduleTableID
References AUTOMATIC, FUNC, GetScheduleTableStatus(), OS_CODE, and VAR.
Referenced by GetScheduleTableStatus().
NextScheduleTable()
StatusType OS_CODE NextScheduleTable (ScheduleTableType ScheduleTableID_From, ScheduleTableType ScheduleTableID_To)
This service switches the processing from one schedule table to another schedule table
Sync/Async: Synchronous
Reentrancy: Reentrant
Reference: AUTOSAR OS 8.4.12 NextScheduleTable [SWS_Os_00191] (SRS_Os_00099)
Parameters
[in] ScheduleTableID_From Currently processed schedule table
[in] ScheduleTableID_To Schedule table that provides its series of expiry points
Returns
The function returns a StatusType.
E_OK No error
E_OS_ID (Extended) ScheduleTableID_From or ScheduleTableID_To not valid.
E_OS_NOFUNC ScheduleTableID_From not started
E_OS_STATE ScheduleTableID_To is started or next
References AUTOMATIC, FUNC, NextScheduleTable(), OS_CODE, and VAR.
Referenced by NextScheduleTable().
StartScheduleTableAbs()
StatusType OS_CODE StartScheduleTableAbs (ScheduleTableType ScheduleTableID, TickType Start)
This service starts the processing of a schedule table at an absolute value "Start" on the underlying counter.
Sync/Async: Synchronous
Reentrancy: Reentrant
Reference: AUTOSAR OS 8.4.10 StartScheduleTableAbs [SWS_Os_00358]
Parameters
[in] ScheduleTableID Schedule table to be started
[in] Start Absolute counter tick value at which the schedule table is started
Returns
The function returns a StatusType.
E_OK No Error.
E_OS_ID (Extended) ScheduleTableID not valid.
E_OS_VALUE (Extended) "Start" is greater than OsCounterMaxAllowedValue.
E_OS_STATE Schedule table was already started.
References AUTOMATIC, FUNC, OS_CODE, StartScheduleTableAbs(), and VAR.
Referenced by StartScheduleTableAbs().
StartScheduleTableRel()
StatusType OS_CODE StartScheduleTableRel (ScheduleTableType ScheduleTableID, TickType Offset)
This service starts the processing of a schedule table at "Offset" relative to the "Now" value on the underlying counter.
Sync/Async: Synchronous
Reentrancy: Reentrant
Reference: AUTOSAR OS 8.4.9 StartScheduleTableRel [SWS_Os_00347]
Parameters
[in] ScheduleTableID Schedule table to be started.
[in] Offset Number of ticks on the counter before the the schedule table processing is started
Returns
The function returns a StatusType.
E_OK No Error.
E_OS_ID (Extended) ScheduleTableID not valid.
E_OS_VALUE (Extended) Offset is greater than (OsCounterMaxAllowedValue - InitialOffset) or is equal to 0.
E_OS_STATE Schedule table was already started.
References AUTOMATIC, FUNC, OS_CODE, StartScheduleTableRel(), and VAR.
Referenced by StartScheduleTableRel().
StopScheduleTable()
StatusType OS_CODE StopScheduleTable (ScheduleTableType ScheduleTableID)
This service cancels the processing of a schedule table immediately at any point while the schedule table is running.
Sync/Async: Synchronous
Reentrancy: Reentrant
Reference: AUTOSAR OS 8.4.11 StopScheduleTable [SWS_Os_00006]
Parameters
[in] ScheduleTableID Schedule table to be stopped
Returns
The function returns a StatusType.
E_OK No Error
E_OS_ID (Extended) ScheduleTableID not valid.
E_OS_NOFUNC Schedule table was already stopped.
References AUTOMATIC, FUNC, OS_CODE, StopScheduleTable(), and VAR.
Referenced by StopScheduleTable().
SyncScheduleTable()
StatusType OS_CODE SyncScheduleTable (ScheduleTableType ScheduleTableID, TickType Value)
This service provides the schedule table with a synchronization count and start synchronization.
Sync/Async: Synchronous
Reentrancy: Reentrant
Reference: AUTOSAR OS 8.4.14 SyncScheduleTable [SWS_Os_00199] (SRS_Os_11002)
Parameters
[in] ScheduleTableID Schedule table to be synchronized
[in] Value The current value of the synchronization counter
Returns
The function returns a StatusType.
E_OK No errors
E_OS_ID (Extended) The ScheduleTableID was not valid or schedule table can not be synchronized (OsScheduleTblSyncStrategy not set or OsScheduleTblSyncStrategy = IMPLICIT)
E_OS_VALUE (Extended) The ''Value'' is out of range.
E_OS_STATE The state of schedule table ''ScheduleTableID'' is equal to SCHEDULETABLE_STOPPED
References AUTOMATIC, OS_CODE, SyncScheduleTable(), and VAR.
Referenced by SyncScheduleTable().