Erika3 Manual: Hooks and Error handling primitives
Hooks and Error handling primitives
ERIKA3 supports five application callbacks that are called when specific situations happens during application execution.
Macros
#define OSErrorGetServiceId()
Used to get the current service ID.
#define OSError_ActivateTask_TaskID()
This macro returns the TaskID parameter passed to ActivateTask().
#define OSError_ChainTask_TaskID()
This macro returns the TaskID parameter passed to ChainTask().
#define OSError_GetTaskID_TaskID()
This macro returns the TaskID parameter passed to GetTaskID().
#define OSError_GetTaskState_TaskID()
This macro returns the TaskID parameter passed to GetTaskState().
#define OSError_GetTaskState_State()
This macro returns the State parameter passed to GetTaskState().
#define OSError_ShutdownOS_Error()
This macro returns the Error parameter passed to ShutdownOS().
#define OSError_GetResource_ResID()
This macro returns the ResID parameter passed to GetResource().
#define OSError_ReleaseResource_ResID()
This macro returns the ResID parameter passed to ReleaseResource().
#define OSError_GetAlarm_AlarmID()
This macro returns the AlarmID parameter passed to GetAlarm().
#define OSError_CancelAlarm_AlarmID()
This macro returns the AlarmID parameter passed to GetAlarm().
#define OSError_SetRelAlarm_AlarmID()
This macro returns the AlarmID parameter passed to SetRelAlarm().
#define OSError_SetRelAlarm_increment()
This macro returns the increment parameter passed to SetRelAlarm().
#define OSError_SetRelAlarm_cycle()
This macro returns the cycle parameter passed to SetRelAlarm().
#define OSError_SetAbsAlarm_AlarmID()
This macro returns the AlarmID parameter passed to SetAbsAlarm().
#define OSError_SetAbsAlarm_start()
This macro returns the start parameter passed to SetAbsAlarm().
#define OSError_SetAbsAlarm_cycle()
This macro returns the cycle parameter passed to SetAbsAlarm().
#define OSError_GetAlarmBase_AlarmID()
This macro returns the AlarmID parameter passed to GetAlarmBase().
#define OSError_GetAlarmBase_Info()
This macro returns the Info parameter passed to GetAlarmBase().
#define OSError_WaitEvent_Mask()
This macro returns the Mask parameter passed to WaitEvent().
#define OSError_SetEvent_TaskID()
This macro returns the TaskID parameter passed to SetEvent().
#define OSError_SetEvent_Mask()
This macro returns the Mask parameter passed to SetEvent().
#define OSError_GetEvent_TaskID()
This macro returns the TaskID parameter passed to GetEvent().
#define OSError_GetEvent_Event()
This macro returns the Event parameter passed to GetEvent().
#define OSError_ClearEvent_Mask()
This macro returns the Mask parameter passed to ClearEvent().
#define OSError_GetCounterValue_CounterID()
This macro returns the CounterID parameter passed to GetCounterValue().
#define OSError_GetCounterValue_Value()
This macro returns the Value parameter passed to GetCounterValue().
#define OSError_GetElapsedValue_CounterID()
This macro returns the CounterID parameter passed to GetElapsedValue().
#define OSError_GetElapsedValue_Value()
This macro returns the Value parameter passed to GetElapsedValue().
#define OSError_GetElapsedValue_ElapsedValue()
This macro returns the ElapsedValue parameter passed to GetElapsedValue().
#define OSError_IncrementCounter_CounterID()
This macro returns the CounterID parameter passed to IncrementCounter().
#define OSError_StartScheduleTableRel_ScheduleTableID()
This macro returns the ScheduleTableID parameter passed to StartScheduleTableRel().
#define OSError_StartScheduleTableRel_Offset()
This macro returns the Offset parameter passed to StartScheduleTableRel().
#define OSError_StartScheduleTableAbs_ScheduleTableID()
This macro returns the ScheduleTableID parameter passed to StartScheduleTableAbs().
#define OSError_StartScheduleTableAbs_Start()
This macro returns the Start parameter passed to StartScheduleTableAbs().
#define OSError_StopScheduleTable_ScheduleTableID()
This macro returns the ScheduleTableID parameter passed to StopScheduleTable().
#define OSError_GetScheduleTableStatus_ScheduleTableID()
This macro returns the ScheduleTableID parameter passed to GetScheduleTableStatus().
#define OSError_GetScheduleTableStatus_ScheduleStatus()
This macro returns the ScheduleStatus parameter passed to GetScheduleTableStatus().
#define OSError_NextScheduleTable_ScheduleTableID_From()
This macro returns the From parameter passed to NextScheduleTable().
#define OSError_NextScheduleTable_ScheduleTableID_To()
This macro returns the To parameter passed to NextScheduleTable().
#define OSError_SyncScheduleTable_ScheduleTableID()
This macro returns the ScheduleTableID parameter passed to SyncScheduleTable().
#define OSError_SyncScheduleTable_Value()
This macro returns the Value parameter passed to SyncScheduleTable().
#define OSError_GetSpinlock_SpinlockID()
This macro returns the SpinlockID parameter passed to GetSpinlock().
#define OSError_ReleaseSpinlock_SpinlockID()
This macro returns the SpinlockID parameter passed to ReleaseSpinlock().
#define OSError_TryToGetSpinlock_SpinlockID()
This macro returns the SpinlockID parameter passed to TryToGetSpinlock().
#define OSError_TryToGetSpinlock_Success()
This macro returns the Success parameter passed to TryToGetSpinlock().
Functions
void OS_CODE ErrorHook (StatusType Error)
Hook called when there is an error inside a primitive.
void OS_CODE StartupHook (void)
Called inside StartOS().
void OS_CODE PreTaskHook (void)
Called everytime a task becomes running.
void OS_CODE PostTaskHook (void)
Called everytime a task is no more the running task.
void OS_CODE ShutdownHook (StatusType Error)
Hook called inside ShutdownOS().
OSServiceIdType OS_CODE osEE_get_service_id (void)
Used internally to get the current service ID.
OsEE_api_param OS_CODE osEE_get_api_param1 (void)
Used internally to implement the ErrorHook() macros.
OsEE_api_param OS_CODE osEE_get_api_param2 (void)
Used internally to implement the ErrorHook() macros.
OsEE_api_param OS_CODE osEE_get_api_param3 (void)
Used internally to implement the ErrorHook() macros.
Detailed Description
On multicore systems, hooks are local callbacks to each core.
The ErrorHook() callback is called every time an error is detected inside an ERIKA3 primitive. The callback can be used to implement centralized error handling. A set of macros are also available to better understand the source of the error. In particular, ErrorHook() receives as parameter the error that is raised by the primitive. Then, a call to OSErrorGetServiceId() returns informations about which primitive caused the error. Finally, calls to the macros OSError_XXX_YYY() returns the values of the YYY parameter of the primitive XXX.
The StartupHook() callback is called inside the StartOS() primitive to implement the application startup procedure.
The ShutdownHook() callback is called inside the ShutdownOS() primitive to implement the Application specific shutdown procedures.
The PreTaskHook() and PostTaskHook() callbacks are called respectively every time a task becomes the RUNNING Task, and every time a task stops to be the RUNNING Task.
The application can only call a limited set of primitives inside Hook functions.
Macro Definition Documentation
OSError_ActivateTask_TaskID
#define OSError_ActivateTask_TaskID ()
Value:
  ((TaskType)osEE_get_api_param1().num_param)
OSError_CancelAlarm_AlarmID
#define OSError_CancelAlarm_AlarmID ()
Value:
  ((AlarmType)osEE_get_api_param1().num_param)
OSError_ChainTask_TaskID
#define OSError_ChainTask_TaskID ()
Value:
  ((TaskType)osEE_get_api_param1().num_param)
OSError_ClearEvent_Mask
#define OSError_ClearEvent_Mask ()
Value:
  ((EventMaskType)osEE_get_api_param1().num_param)
OSError_GetAlarm_AlarmID
#define OSError_GetAlarm_AlarmID ()
Value:
  ((AlarmType)osEE_get_api_param1().num_param)
OSError_GetAlarmBase_AlarmID
#define OSError_GetAlarmBase_AlarmID ()
Value:
  ((AlarmType)osEE_get_api_param1().num_param)
OSError_GetAlarmBase_Info
#define OSError_GetAlarmBase_Info ()
Value:
  ((AlarmBaseRefType)osEE_get_api_param2().p_param)
OSError_GetCounterValue_CounterID
#define OSError_GetCounterValue_CounterID ()
Value:
  ((CounterType)osEE_get_api_param1().num_param)
OSError_GetCounterValue_Value
#define OSError_GetCounterValue_Value ()
Value:
  ((TickRefType)osEE_get_api_param2().p_param)
OSError_GetElapsedValue_CounterID
#define OSError_GetElapsedValue_CounterID ()
Value:
  ((CounterType)osEE_get_api_param1().num_param)
OSError_GetElapsedValue_ElapsedValue
#define OSError_GetElapsedValue_ElapsedValue ()
Value:
  ((TickRefType)osEE_get_api_param3().p_param)
OSError_GetElapsedValue_Value
#define OSError_GetElapsedValue_Value ()
Value:
  ((TickRefType)osEE_get_api_param2().p_param)
OSError_GetEvent_Event
#define OSError_GetEvent_Event ()
Value:
  ((EventMaskRefType)osEE_get_api_param2().p_param)
OSError_GetEvent_TaskID
#define OSError_GetEvent_TaskID ()
Value:
  ((TaskType)osEE_get_api_param1().num_param)
OSError_GetResource_ResID
#define OSError_GetResource_ResID ()
Value:
  ((ResourceType)osEE_get_api_param1().num_param)
OSError_GetScheduleTableStatus_ScheduleStatus
#define OSError_GetScheduleTableStatus_ScheduleStatus ()
Value:
  ((ScheduleTableStatusRefType)osEE_get_api_param2().p_param)
OSError_GetScheduleTableStatus_ScheduleTableID
#define OSError_GetScheduleTableStatus_ScheduleTableID ()
Value:
  ((ScheduleTableType)osEE_get_api_param1().num_param)
OSError_GetSpinlock_SpinlockID
#define OSError_GetSpinlock_SpinlockID ()
Value:
  ((SpinlockIdType)osEE_get_api_param1().num_param)
OSError_GetTaskID_TaskID
#define OSError_GetTaskID_TaskID ()
Value:
  ((TaskRefType)osEE_get_api_param1().p_param)
OSError_GetTaskState_State
#define OSError_GetTaskState_State ()
Value:
  ((TaskRefType)osEE_get_api_param2().p_param)
OSError_GetTaskState_TaskID
#define OSError_GetTaskState_TaskID ()
Value:
  ((TaskType)osEE_get_api_param1().num_param)
OSError_IncrementCounter_CounterID
#define OSError_IncrementCounter_CounterID ()
Value:
  ((CounterType)osEE_get_api_param1().num_param)
OSError_NextScheduleTable_ScheduleTableID_From
#define OSError_NextScheduleTable_ScheduleTableID_From ()
Value:
  ((ScheduleTableType)osEE_get_api_param1().num_param)
OSError_NextScheduleTable_ScheduleTableID_To
#define OSError_NextScheduleTable_ScheduleTableID_To ()
Value:
  ((ScheduleTableType)osEE_get_api_param2().num_param)
OSError_ReleaseResource_ResID
#define OSError_ReleaseResource_ResID ()
Value:
  ((ResourceType)osEE_get_api_param1().num_param)
OSError_ReleaseSpinlock_SpinlockID
#define OSError_ReleaseSpinlock_SpinlockID ()
Value:
  ((SpinlockIdType)osEE_get_api_param1().num_param)
OSError_SetAbsAlarm_AlarmID
#define OSError_SetAbsAlarm_AlarmID ()
Value:
  ((AlarmType)osEE_get_api_param1().num_param)
OSError_SetAbsAlarm_cycle
#define OSError_SetAbsAlarm_cycle ()
Value:
  ((TickType)osEE_get_api_param3().num_param)
OSError_SetAbsAlarm_start
#define OSError_SetAbsAlarm_start ()
Value:
  ((TickType)osEE_get_api_param2().num_param)
OSError_SetEvent_Mask
#define OSError_SetEvent_Mask ()
Value:
  ((EventMaskType)osEE_get_api_param2().num_param)
OSError_SetEvent_TaskID
#define OSError_SetEvent_TaskID ()
Value:
  ((TaskType)osEE_get_api_param1().num_param)
OSError_SetRelAlarm_AlarmID
#define OSError_SetRelAlarm_AlarmID ()
Value:
  ((AlarmType)osEE_get_api_param1().num_param)
OSError_SetRelAlarm_cycle
#define OSError_SetRelAlarm_cycle ()
Value:
  ((TickType)osEE_get_api_param3().num_param)
OSError_SetRelAlarm_increment
#define OSError_SetRelAlarm_increment ()
Value:
  ((TickType)osEE_get_api_param2().num_param)
OSError_ShutdownOS_Error
#define OSError_ShutdownOS_Error ()
Value:
  ((StatusType)osEE_get_api_param1().num_param)
OSError_StartScheduleTableAbs_ScheduleTableID
#define OSError_StartScheduleTableAbs_ScheduleTableID ()
Value:
  ((ScheduleTableType)osEE_get_api_param1().num_param)
OSError_StartScheduleTableAbs_Start
#define OSError_StartScheduleTableAbs_Start ()
Value:
  ((TickType)osEE_get_api_param2().num_param)
OSError_StartScheduleTableRel_Offset
#define OSError_StartScheduleTableRel_Offset ()
Value:
  ((TickType)osEE_get_api_param2().num_param)
OSError_StartScheduleTableRel_ScheduleTableID
#define OSError_StartScheduleTableRel_ScheduleTableID ()
Value:
  ((ScheduleTableType)osEE_get_api_param1().num_param)
OSError_StopScheduleTable_ScheduleTableID
#define OSError_StopScheduleTable_ScheduleTableID ()
Value:
  ((ScheduleTableType)osEE_get_api_param1().num_param)
OSError_SyncScheduleTable_ScheduleTableID
#define OSError_SyncScheduleTable_ScheduleTableID ()
Value:
  ((ScheduleTableType)osEE_get_api_param1().num_param)
OSError_SyncScheduleTable_Value
#define OSError_SyncScheduleTable_Value ()
Value:
  ((TickType)osEE_get_api_param2().num_param)
OSError_TryToGetSpinlock_SpinlockID
#define OSError_TryToGetSpinlock_SpinlockID ()
Value:
  ((SpinlockIdType)osEE_get_api_param1().num_param)
OSError_TryToGetSpinlock_Success
#define OSError_TryToGetSpinlock_Success ()
Value:
  ((TryToGetSpinlockType)osEE_get_api_param2().p_param)
OSError_WaitEvent_Mask
#define OSError_WaitEvent_Mask ()
Value:
  ((EventMaskType)osEE_get_api_param1().num_param)
OSErrorGetServiceId
#define OSErrorGetServiceId ()
Value:
osEE_get_service_id()
Returns
The function returns the last primitive called in the current core.
Function Documentation
ErrorHook()
void OS_CODE ErrorHook (StatusType Error)
When configured in the OIL File, the system calls this callback every time the return value of a function is different from E_OK. The application can then get additional informations using the OSErrorGetServiceId() macro, that returns the function that is generating the Error. Once the function that generated the error is known, the application can also access the parameters that generated the error using the OSError_XXX_YYY() macros, where XXX is the name of the function, and YYY is the name of the parameter passed to the function.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.9.2.1
Parameters
[in] Error The error which triggered the call.
References AUTOMATIC, ErrorHook(), OS_CODE, and VAR.
Referenced by ErrorHook().
osEE_get_api_param1()
OsEE_api_param OS_CODE osEE_get_api_param1 (void)
Not to be called directly in user code.
Returns
The function returns a OsEE_api_param, which is a union containing the first parameter value.
References FUNC, OS_CODE, and osEE_get_api_param1().
Referenced by osEE_get_api_param1().
osEE_get_api_param2()
OsEE_api_param OS_CODE osEE_get_api_param2 (void)
Not to be called directly in user code.
Returns
The function returns a OsEE_api_param, which is a union containing the second parameter value.
References FUNC, OS_CODE, and osEE_get_api_param2().
Referenced by osEE_get_api_param2().
osEE_get_api_param3()
OsEE_api_param OS_CODE osEE_get_api_param3 (void)
Not to be called directly in user code.
Returns
The function returns a OsEE_api_param, which is a union containing the third parameter value.
References osEE_get_api_param3().
Referenced by osEE_get_api_param3().
osEE_get_service_id()
OSServiceIdType OS_CODE osEE_get_service_id (void)
Not to be called directly in user code.
Returns
The function returns the last primitive called in the current core.
References osEE_get_service_id().
Referenced by osEE_get_service_id().
PostTaskHook()
void OS_CODE PostTaskHook (void)
When configured in the OIL File, this hook function is called every time a task is no more the RUNNING task due to the call of other functions, or due to the preemption done by interrupts. The ID of the task which has just finished to be the RUNNING task can be read using the GetTaskID() function.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.9.2.3
References OS_CODE, and PostTaskHook().
Referenced by PostTaskHook().
PreTaskHook()
void OS_CODE PreTaskHook (void)
When configured in the OIL File, this hook function is called every time a task becomes the RUNNING task due to the call of other functions, or due to the preemption done by interrupts. The ID of the task which has just become the RUNNING task can be read using the GetTaskID() function.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.9.2.2
References OS_CODE, and PreTaskHook().
Referenced by PreTaskHook().
ShutdownHook()
void OS_CODE ShutdownHook (StatusType Error)
When configured in the OIL File, this hook function is called inside ShutdownOS(). Inside this callback, the Application can implement application dependent shutdown functions.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.9.2.5
Parameters
[in] Error this is the Error condition originally passed to ShutdownOS().
References AUTOMATIC, OS_CODE, ShutdownHook(), and VAR.
Referenced by ShutdownHook().
StartupHook()
void OS_CODE StartupHook (void)
When configured in the OIL File, this hook function is called inside StartOS(). Inside this callback, the Application can call the Operating System-related functions ActivateTask(), SetRelAlarm(), and SetAbsAlarm(). Please note that the simplest way to activate a task or set an alarm at startup is to specify their initial activation/setting inside the OIL File.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.9.2.4
References OS_CODE, and StartupHook().
Referenced by StartupHook().