Erika3 Manual: Interrupt Primitives
Interrupt Primitives
The Interrupt primitives are related to disabling/enabling interrupts.
Macros
#define INVALID_ISR INVALID_TASK
This is the invalid ISR2 value.
Typedefs
typedef OSEE_TASK_ID_TYPE ISRType
Type used for interrupts type 2.
typedef OSEE_ISR_SOURCE_TYPE ISRSource
This type stores an interrupt source type.
Functions
void OS_CODE DisableAllInterrupts (void)
Disables all interrupts.
void OS_CODE EnableAllInterrupts (void)
Enables all interrupts.
void OS_CODE SuspendAllInterrupts (void)
Disables interrupt, saving the current status.
void OS_CODE ResumeAllInterrupts (void)
Resumes the interrupt status saved with SuspendAllInterrupts().
void OS_CODE SuspendOSInterrupts (void)
Disables ISR2 interrupt, saving the current status.
void OS_CODE ResumeOSInterrupts (void)
Resumes the interrupt status saved with SuspendOSInterrupts().
ISRType OS_CODE GetISRID (void)
Gets the ID of the running ISR.
Detailed Description
ERIKA3 provides support for interrupts. Interrupts are modeled considering typical microcontroller designs featuring interrupt controllers with a prioritized view of the interrupt sources.
To map the requirements of fast OS-independent requests, ERIKA3 supports the definition of fast interrupts handlers, called ISR Type 1, that on one side can handle interrupts in the fastest way possible, but on the other side lack the possibility to call OS services.
On the other end, lower priority interrupts, called ISR Type 2 and used (for example) for hardware timers, can call selected OS primitives but are slower than ISR Type 1 due to the OS bookkeeping needed to implement preemption.
Please also note that ISR Type 2 are implemented in ERIKA3 in a way similar to Tasks, to allow a simpler handling of the Memory protection specification of the AUTOSAR OS.
The following restriction applies: all interrupts of Category 1 must have a higher or equal hardware priority compared with interrupts of Category 2. This limitation has been introduced to avoid various rescheduling problems appearing when a ISR2 interrupts a lower priority ISR1.
ERIKA3 also offers a set of primitives to directly control interrupt disabling and enabling, with also a nested version of these primitives.
Macro Definition Documentation
INVALID_ISR
#define INVALID_ISR INVALID_TASK
This is the invalid ISR2 value. No real ISR can have this value.
Typedef Documentation
ISRSource
typedef OSEE_ISR_SOURCE_TYPE ISRSource
This type stores an interrupt source type.
ISRType
typedef OSEE_TASK_ID_TYPE ISRType
Type used for interrupts type 2. It is a positive number. The ISR2 IDs are in the same value space as Task IDs (this because ISR2 in ERIKA3 are implemented in a way similar to tasks).
Function Documentation
DisableAllInterrupts()
void OS_CODE DisableAllInterrupts (void)
DisableAllInterrupts() and EnableAllInterrupts() are used to implement critical sections with interrupt disabled.
This primitive disables all the interrupts sources in the system, and saves the interrupt state that will be restored by a call to EnableAllInterrupts().
The primitive may be called from an ISR category 1 and category 2 and from the task level, but not from hook routines. No primitives can be called within critical sections surrounded by DisableAllInterrupts() and EnableAllInterrupts().
Critical sections using DisableAllInterrupts() and EnableAllInterrupts() cannot be nested. If you need nested critical sections, please use SuspendOSInterrupts() / ResumeOSInterrupts() or SuspendAllInterrupts() / ResumeAllInterrupts().
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.4.2.2
References DisableAllInterrupts(), FUNC, and OS_CODE.
Referenced by DisableAllInterrupts().
EnableAllInterrupts()
void OS_CODE EnableAllInterrupts (void)
DisableAllInterrupts() and EnableAllInterrupts() are used to implement critical sections with interrupt disabled.
This primitive restores the state saved by DisableAllInterrupts(), enabling the recognition of interrupts.
The primitive may be called from an ISR category 1 and category 2 and from the task level, but not from hook routines. No primitives can be called inside critical sections surrounded by DisableAllInterrupts() and EnableAllInterrupts().
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.4.2.1
References EnableAllInterrupts(), FUNC, and OS_CODE.
Referenced by EnableAllInterrupts().
GetISRID()
ISRType OS_CODE GetISRID (void)
If called inside an ISR2, it returns the ID of the current executing ISR.
Reference: AUTOSAR OS 8.4.3 GetISRID [SWS_Os_00511]
Returns
This function returns a ISRType which is the current executing ISR or INVALID_ISR if called outside an ISR Routine (or Hooks called inside an ISR2 routine).
References GetISRID(), LOCAL_INLINE, and OS_CODE.
Referenced by GetISRID().
ResumeAllInterrupts()
void OS_CODE ResumeAllInterrupts (void)
SuspendAllInterrupts() and ResumeAllInterrupts() are used to implement critical sections with interrupt disabled, with nesting support.
This primitive restores the state saved by SuspendAllInterrupts(), enabling the recognition of interrupts if it is the last call in a series of nested calls of SuspendAllInterrupts() / ResumeAllInterrupts() and SuspendOSInterrupts() / ResumeOSInterrupts() pairs.
This primitive may be called from an ISR category 1 and category 2, from alarm-callbacks and from the task level, but not from all hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.4.2.3
References FUNC, OS_CODE, and ResumeAllInterrupts().
Referenced by ResumeAllInterrupts().
ResumeOSInterrupts()
void OS_CODE ResumeOSInterrupts (void)
SuspendOSInterrupts() and ResumeOSInterrupts() are used to implement critical sections with interrupt category 2 disabled, with nesting support.
This primitive restores the state saved by SuspendOSInterrupts(), enabling the recognition of interrupts if it is the last call in a series of nested calls of SuspendAllInterrupts() / ResumeAllInterrupts() and SuspendOSInterrupts() / ResumeOSInterrupts() pairs.
The primitive may be called from an ISR category 1 and category 2 and from the task level, but not from hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.4.2.5
References FUNC, OS_CODE, and ResumeOSInterrupts().
Referenced by ResumeOSInterrupts().
SuspendAllInterrupts()
void OS_CODE SuspendAllInterrupts (void)
SuspendAllInterrupts() and ResumeAllInterrupts() are used to implement critical sections with interrupt disabled, with nesting support.
This primitive disables all the interrupts sources in the system, and saves the interrupt state that will be restored by a call to ResumeAllInterrupts().
The service may be called from an ISR category 1 and category 2, from alarm-callbacks and from the task level, but not from all hook routines.
No primitive calls beside SuspendAllInterrupts() / ResumeAllInterrupts() pairs and SuspendOSInterrupts() / ResumeOSInterrupts() pairs are allowed within this critical section.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.4.2.4
References FUNC, OS_CODE, and SuspendAllInterrupts().
Referenced by SuspendAllInterrupts().
SuspendOSInterrupts()
void OS_CODE SuspendOSInterrupts (void)
SuspendOSInterrupts() and ResumeOSInterrupts() are used to implement critical sections with interrupt category 2 disabled, with nesting support.
This primitive disables all the interrupts sources of category 2 in the system, and saves the interrupt state that will be restored by a call to ResumeOSInterrupts().
The service may be called from an ISR category 1 and category 2, and from the task level.
No primitive calls beside SuspendAllInterrupts() / ResumeAllInterrupts() pairs and SuspendOSInterrupts() / ResumeOSInterrupts() pairs are allowed within this critical section.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.4.2.6
References FUNC, OS_CODE, and SuspendOSInterrupts().
Referenced by SuspendOSInterrupts().