Erika3 Manual: inc/ee_get_kernel_and_core.h File Reference
ee_get_kernel_and_core.h File Reference
HAL internal.
#include "ee_platform_types.h"
#include "ee_kernel_types.h"
Functions
OSEE_STATIC_INLINE OsEE_CDB * osEE_get_curr_core (void)
Returns the pointer to CDB.
OSEE_STATIC_INLINE OsEE_CDB * osEE_get_core (CoreIdType core_id)
Returns a pointer to the CDB.
OSEE_STATIC_INLINE OsEE_KDB * osEE_get_kernel (void)
Returns the pointer to the Kernel descriptor Block.
OSEE_STATIC_INLINE void osEE_lock_kernel (void)
Locks the kernel.
OSEE_STATIC_INLINE OsEE_KDB * osEE_lock_and_get_kernel (void)
Locks the kernel and gets the Kernel Descriptor Block pointer.
OSEE_STATIC_INLINE void osEE_unlock_kernel (void)
Unlocks the kernel.
OSEE_STATIC_INLINE CoreIdType osEE_lock_and_get_curr_core_id (void)
Locks the kernel and gets the current core ID.
OSEE_STATIC_INLINE void osEE_lock_core_id (CoreIdType core_id)
Locks a specific core ID.
OSEE_STATIC_INLINE void osEE_lock_core (OsEE_CDB *const p_cdb)
Locks a specific core.
OSEE_STATIC_INLINE OsEE_CDB * osEE_lock_and_get_core (CoreIdType core_id)
Locks a specific core and gets its data structure.
OSEE_STATIC_INLINE OsEE_CDB * osEE_lock_and_get_curr_core (void)
Locks the current core and gets its data structure.
OSEE_STATIC_INLINE void osEE_unlock_core_id (CoreIdType core_id)
Unlocks a specific core.
OSEE_STATIC_INLINE void osEE_unlock_core (OsEE_CDB *const p_cdb)
Unlocks a specific core.
OSEE_STATIC_INLINE void osEE_unlock_curr_core (void)
Unlocks the current core.
Variables
OsEE_KDB osEE_kdb_var
KDB - Kernel Descriptor Block.
OsEE_CDB osEE_cdb_var
CDB - Core Descriptor Block.
OsEE_KCB osEE_kcb_var
KCB - Kernel Control Block.
OsEE_CCB osEE_ccb_var
CCB - Core Control Block.
Detailed Description
This files contains kernel and core entry points data structures retrieving and locking functions.
Author
Errico Guidieri
Giuseppe Serano
Date
2018
Function Documentation
osEE_get_core()
OSEE_STATIC_INLINE OsEE_CDB * osEE_get_core (CoreIdType core_id)
The function returns the pointer to the CDB of the core specified as parameter. Since the machine is a single core machine, the function returns the only CDB available.
Parameters
[in] core_id The core for which we should return the information
Returns
Always returns the only CDB available (it's a single core machine)
References osEE_cdb_var, and OSEE_STATIC_INLINE.
osEE_get_curr_core()
OSEE_STATIC_INLINE OsEE_CDB * osEE_get_curr_core (void)
This function is called internally to get the CDB pointer, which contains the information related to the only core available.
Returns
The function returns a ponter to the CDB data structure of the unique core available.
References osEE_cdb_var, and OSEE_STATIC_INLINE.
Referenced by osEE_lock_and_get_core(), and osEE_lock_and_get_curr_core().
osEE_get_kernel()
OSEE_STATIC_INLINE OsEE_KDB * osEE_get_kernel (void)
The KDB is the data structure containing the global kernel information. This function returns a pointer to it.
Returns
The function returns the pointer to the KDB block
References osEE_kdb_var, and OSEE_STATIC_INLINE.
Referenced by osEE_lock_and_get_kernel().
osEE_lock_and_get_core()
OSEE_STATIC_INLINE OsEE_CDB * osEE_lock_and_get_core (CoreIdType core_id)
Similar to osEE_lock_and_get_curr_core_id(), but it returns a CDB pointer instead of returning the ID. The locking is void on single core configurations.
Parameters
[in] core_id The ID of the core to lock
Returns
The function returns a pointer to the CDB pointer
References osEE_get_curr_core(), and OSEE_STATIC_INLINE.
osEE_lock_and_get_curr_core()
OSEE_STATIC_INLINE OsEE_CDB * osEE_lock_and_get_curr_core (void)
Similar to osEE_lock_and_get_curr_core_id(), but it returns a CDB pointer instead of returning the ID. The locking is void on single core configurations.
Returns
The function returns a pointer to the CDB pointer of the current core
References osEE_get_curr_core(), and OSEE_STATIC_INLINE.
osEE_lock_and_get_curr_core_id()
OSEE_STATIC_INLINE CoreIdType osEE_lock_and_get_curr_core_id (void)
On single core machines, there is no kernel locking. The function returns the current core ID, which is the only one available, 0.
Returns
On single core machines, it returns ID 0, which is the first core.
References OSEE_STATIC_INLINE.
osEE_lock_and_get_kernel()
OSEE_STATIC_INLINE OsEE_KDB * osEE_lock_and_get_kernel (void)
On single core machines, there is no lock. The function therefore has the same effect as osEE_get_kernel().
Returns
This function returnd the Kernel Descriptor Block pointer
References osEE_get_kernel(), osEE_lock_kernel(), and OSEE_STATIC_INLINE.
osEE_lock_core()
OSEE_STATIC_INLINE void osEE_lock_core (OsEE_CDB *const p_cdb)
Similar to osEE_lock_core_id(), but it receives a CDB pointer instead of the ID. Void on single core configurations.
Parameters
[in] p_cdb The core to lock
References OSEE_STATIC_INLINE.
osEE_lock_core_id()
OSEE_STATIC_INLINE void osEE_lock_core_id (CoreIdType core_id)
On multicore machines, there is the need to lock a specific core (e.g. because we have to activate a remote task, which is implemented with a direct modification of the kernel data structures of the remote core).
Since this is a single core configuration, this dunction is void.
Parameters
[in] core_id The core to lock
References OSEE_STATIC_INLINE.
osEE_lock_kernel()
OSEE_STATIC_INLINE void osEE_lock_kernel (void)
On single core machines this function is void since there is no locking of the kernel.
References OSEE_STATIC_INLINE.
Referenced by osEE_lock_and_get_kernel().
osEE_unlock_core()
OSEE_STATIC_INLINE void osEE_unlock_core (OsEE_CDB *const p_cdb)
Unlocks a core whose CDB pointer has been passed as parameter. Void on single core machines.
Parameters
[in] p_cdb The core ID to unlock
References OSEE_STATIC_INLINE.
osEE_unlock_core_id()
OSEE_STATIC_INLINE void osEE_unlock_core_id (CoreIdType core_id)
Unlocks a core whose ID has been passed as parameter. Void on single core machines.
Parameters
[in] core_id The core ID to unlock
References OSEE_STATIC_INLINE.
osEE_unlock_curr_core()
OSEE_STATIC_INLINE void osEE_unlock_curr_core (void)
Unlocks the current core. Void on single core machines.
References OSEE_STATIC_INLINE.
osEE_unlock_kernel()
OSEE_STATIC_INLINE void osEE_unlock_kernel (void)
On single core machines this function is void since there is no locking of the kernel.
References OSEE_STATIC_INLINE.
Variable Documentation
osEE_ccb_var
OsEE_CCB osEE_ccb_var extern
Data structure in RAM that stores information about one of the available croes
osEE_cdb_var
OsEE_CDB osEE_cdb_var extern
Data structure in FLASH that stores information about one of the available cores
Referenced by osEE_get_core(), and osEE_get_curr_core().
osEE_kcb_var
OsEE_KCB osEE_kcb_var extern
Data structure in RAM that stores information about the kernel
osEE_kdb_var
OsEE_KDB osEE_kdb_var extern
Data structure in FLASH that stores information about the kernel
Referenced by osEE_get_kernel().