Erika3 Manual: Multicore support
Multicore support
ERIKA3 has been designed with native multicore support.
Macros
#define INVALID_CORE_ID ((CoreIdType)-1)
Invalid core ID.
Typedefs
typedef OSEE_CORE_ID_TYPE CoreIdType
Type representing a logical core ID.
typedef OSEE_CORE_NUM_TYPE CoreNumType
Type used to store the total number of cores.
typedef OSEE_CORE_MASK_TYPE CoreMaskType
Type representing a mask of cores.
Enumerations
enum TryToGetSpinlockType { TRYTOGETSPINLOCK_NOSUCCESS = 0x0 , TRYTOGETSPINLOCK_SUCCESS }
Type used to indicate if a spinlock has been occupied or not.
Functions
OSEE_STATIC_INLINE CoreIdType OS_CODE GetCoreID (void)
Gets the ID of the running core.
CoreNumType OS_CODE GetNumberOfActivatedCores (void)
Returns the number of cores.
void OS_CODE StartCore (CoreIdType CoreID, StatusType *OS_APPL_DATA Status)
Starts the core specified as parameter.
void OS_CODE StartNonAutosarCore (CoreIdType CoreID, StatusType *OS_APPL_DATA Status)
Starts the core specified as parameter.
void OS_CODE ShutdownAllCores (StatusType Error)
Shut down all cores.
StatusType OS_CODE GetSpinlock (SpinlockIdType SpinlockID)
Lock a spin-lock variable.
StatusType OS_CODE ReleaseSpinlock (SpinlockIdType SpinlockID)
Releases a spin-lock variable.
StatusType OS_CODE TryToGetSpinlock (SpinlockIdType SpinlockID, TryToGetSpinlockType *OS_APPL_DATA Success)
Lock a spin-lock variable, without active waiting.
Detailed Description
These functions are the set of functions which are available to control the execution on multiple cores.
These functions follow closely the AUTOSAR OS Multicore specification.
Macro Definition Documentation
INVALID_CORE_ID
#define INVALID_CORE_ID ((CoreIdType)-1)
A constant representing an invalid logical core ID.
Typedef Documentation
CoreIdType
typedef OSEE_CORE_ID_TYPE CoreIdType
This type represents a logical core ID. Depending on the architectures, this type can be implemented as an enum.
CoreMaskType
typedef OSEE_CORE_MASK_TYPE CoreMaskType
This type represents a mask of cores. Each core is represented with a bit on a bitmask.
CoreNumType
typedef OSEE_CORE_NUM_TYPE CoreNumType
This type is used to store the total number of cores.
Enumeration Type Documentation
TryToGetSpinlockType
enum TryToGetSpinlockType
The TryToGetSpinlockType indicates if the spinlock has been occupied or not.
Function Documentation
GetCoreID()
OSEE_STATIC_INLINE CoreIdType OS_CODE GetCoreID (void)
This function returns the logical core on which the function is being called
Reference: AUTOSAR OS 8.4.24 GetCoreID [SWS_Os_00674]
Returns
This function returns a CoreIdType which is the current core where the function is being called.
References GetCoreID(), and osEE_get_curr_core_id().
Referenced by GetCoreID().
GetNumberOfActivatedCores()
CoreNumType OS_CODE GetNumberOfActivatedCores (void)
This function returns the number of cores of the configuration.
Please note that the returned type is CoreNumType and not uint32 as in the AUTOSAR OS specification.
Reference: AUTOSAR OS 8.4.23 GetNumberOfActivatedCores [SWS_Os_00672]
Returns
This function returns a CoreIdType which is the current core where the function is being called.
References FUNC, GetNumberOfActivatedCores(), and OS_CODE.
Referenced by GetNumberOfActivatedCores().
GetSpinlock()
StatusType OS_CODE GetSpinlock (SpinlockIdType SpinlockID)
This function locks a spin-lock (which is an active wait used to implement mutual exclusions on multicores). The primitive does not implementa a preemption.
Reference: AUTOSAR OS 8.4.27 StartNonAutosarCore [SWS_Os_00686]
Parameters
[in] SpinlockID The spin lock to be locked
Returns
The function returns a StatusType.
E_OK No Error
E_OS_ID (Extended) The spin lock is invalid
E_OS_INTERFERENCE_DEADLOCK (Extended) Lock already taken on the same core.
E_OS_NESTING_DEADLOCK (Extended) another Task on the same core is taking another spinlock
E_OS_ACCESS (Extended) The spin lock cannot be accessed
References AUTOMATIC, FUNC, GetSpinlock(), OS_CODE, and VAR.
Referenced by GetSpinlock().
ReleaseSpinlock()
StatusType OS_CODE ReleaseSpinlock (SpinlockIdType SpinlockID)
This function releases a spin-lock which was previously locked.
All spin locks must be released before terminating or before calling WaitEvent().
Reference: AUTOSAR OS 8.4.28 ReleaseSpinlock [SWS_Os_00695]
Parameters
[in] SpinlockID The spin lock to be locked
Returns
The function returns a StatusType.
E_OK No Error.
E_OS_ID (Extended) The spin lock is invalid.
E_OS_STATE (Extended) The spin lock is not occupied by the calling task.
E_OS_ACCESS (Extended) The spin lock cannot be accessed.
E_OS_NOFUNC (Extended) Another spinlock has to be released before.
References AUTOMATIC, FUNC, OS_CODE, ReleaseSpinlock(), and VAR.
Referenced by ReleaseSpinlock().
ShutdownAllCores()
void OS_CODE ShutdownAllCores (StatusType Error)
This function shut down the calling core. it never returns. it also forces all other cores to shut down.
Reference: AUTOSAR OS 8.4.30 ShutdownAllCores [SWS_Os_00713]
Parameters
[in] Error The error to be passed to the ShutdownHook()
References AUTOMATIC, OS_CODE, ShutdownAllCores(), and VAR.
Referenced by ShutdownAllCores().
StartCore()
void OS_CODE StartCore (CoreIdType CoreID, StatusType *OS_APPL_DATA Status)
This function starts the core specified as parameter.
The function shall be called before StartOS. the activated core must call StartOS() once activated.
Reference: AUTOSAR OS 8.4.25 StartCore [SWS_Os_00676]
Parameters
[in] CoreID The core to be activated
[out] Status The status returned by the function:
E_OK No Error
E_OS_ID Core ID is invalid
E_OS_ACCESS The function was called after starting the OS.
E_OS_STATE The Core is already activated.
References AUTOMATIC, FUNC, OS_APPL_DATA, OS_CODE, P2VAR, StartCore(), and VAR.
Referenced by StartCore().
StartNonAutosarCore()
void OS_CODE StartNonAutosarCore (CoreIdType CoreID, StatusType *OS_APPL_DATA Status)
This function starts the core specified as parameter.
It is allowed to call the function after StartOS(). the activated core must call StartOS() once activated.
Reference: AUTOSAR OS 8.4.26 StartNonAutosarCore [SWS_Os_00682]
Parameters
[in] CoreID The core to be activated
[out] Status The status returned by the function:
E_OK No Error
E_OS_ID Core ID is invalid
E_OS_STATE The Core is already activated.
References AUTOMATIC, FUNC, OS_APPL_DATA, OS_CODE, P2VAR, StartNonAutosarCore(), and VAR.
Referenced by StartNonAutosarCore().
TryToGetSpinlock()
StatusType OS_CODE TryToGetSpinlock (SpinlockIdType SpinlockID, TryToGetSpinlockType *OS_APPL_DATA Success)
This function locks a spin-lock in a similar way to GetSpinlock(), but it does it without an active loop. The result of the first check is returned in the Success parameter.
Reference: AUTOSAR OS 8.4.29 TryToGetSpinlock [SWS_Os_00703]
Parameters
[in] SpinlockID The spin lock to be locked
[out] Success The result of the trylock operation
Returns
The function returns a StatusType.
E_OK No Error
E_OS_ID (Extended) The spin lock is invalid
E_OS_INTERFERENCE_DEADLOCK (Extended) Lock already taken on the same core.
E_OS_NESTING_DEADLOCK (Extended) another Task on the same core is taking another spinlock
E_OS_ACCESS (Extended) The spin lock cannot be accessed
References AUTOMATIC, OS_APPL_DATA, OS_CODE, P2VAR, TryToGetSpinlock(), and VAR.
Referenced by TryToGetSpinlock().