Erika3 Manual: Alarm and Counter Primitives
Alarm and Counter Primitives
The Alarm Primitives are related to periodic or one-shot notification useful to implement timeouts or periodic activities.
Data Structures
struct TYPEDEF
The AlarmBaseType stores information about a counter.
Macros
#define INVALID_ALARM ((AlarmType)-1)
Invalid alarm ID.
#define DeclareAlarm(Alarm)
Alarm Declaration.
#define ALARMCALLBACK(cbk)
This macro is used both to declare and to define an alarm callback.
Typedefs
typedef OSEE_COUNTER_TYPE CounterType
Type representing a counter.
typedef OSEE_TICK_TYPE TickType
Type representing the value of ticks a counter can store.
typedef TickType TYPEDEF *OS_APPL_DATA TickRefType
This is a pointer to a TickType.
typedef struct TYPEDEF AlarmBaseType
The AlarmBaseType stores information about a counter.
typedef OSEE_ALARM_ID_TYPE AlarmType
Type for Alarm IDs.
Functions
StatusType OS_CODE SetRelAlarm (AlarmType AlarmID, TickType increment, TickType cycle)
Arm the alarm based on a relative counter value.
StatusType OS_CODE SetAbsAlarm (AlarmType AlarmID, TickType start, TickType cycle)
Arm the alarm based on a absolute counter value.
StatusType OS_CODE GetAlarm (AlarmType AlarmID, TickRefType Tick)
Returns relative tick value before alarm expiration.
StatusType OS_CODE GetAlarmBase (AlarmType AlarmID, AlarmBaseRefType Info)
Returns the alarm base characteristics.
StatusType OS_CODE CancelAlarm (AlarmType AlarmID)
Cancels an active alarm.
StatusType OS_CODE GetCounterValue (CounterType CounterID, TickRefType Value)
Reads a counter value.
StatusType OS_CODE GetElapsedValue (CounterType CounterID, TickRefType Value, TickRefType ElapsedValue)
Gets the number of ticks since the last read.
StatusType OS_CODE IncrementCounter (CounterType CounterID)
Increment a software counter.
Detailed Description
ERIKA3 supports a notification mechanism based on Counters and Alarms.
A Counter is basically an integer value that can be incremented by 1 _Tick using the primitive IncrementCounter().
An Alarm is a notification that is attached to a specific Counter (the link between a Counter and an Alarm is specified at compile time in the OIL Configuration file).
An Alarm can be set to fire at a specified tick value using the primitives SetRelAlarm() and SetAbsAlarm(). Alarms can be set to be cyclically reactivated. Alarms can be canceled using the primitive CancelAlarm().
When an Alarm fires, a notification takes place. A notification is set to be one of the following actions:
Task activation. In this case, a task is activated when the Alarm fires.
Event set. In this case, an event mask is set on a task when the Alarm fires.
Alarm callback. In this case, an alarm callback (defined using ALARMCALLBACK()) is called. Alarm callbacks are DEPRECATED by AUTOSAR.
The notifications are executed inside the IncrementCounter() function. It is up to the developer placing the counter in meaningful places (e.g., a timer interrupt).
Counters, Alarms, and their notifications are specified inside the OIL configuration file.
On multicore systems, Counters are statically assigned to CPUs at compile time. Counters are local to (and only visible in) a CPU. Alarms are local to the CPU that hosts the counter they are linked to.
The OSEK/VDX standard provides support for System Counters (e.g., counters that are automatically linked to hardware timers). Please check on the ERIKA3 wiki whether the architecture you are using supports this feature (especially for the configuration of the hardware interrupt source). If the architecture does not support the feature, then all the counters have to be defined inside the OIL Configuration file, and the user have to call IncrementCounter() to increment them.
Macro Definition Documentation
ALARMCALLBACK
#define ALARMCALLBACK (cbk)
Value:
void cbk (void)
This macro is used both to declare and to define an alarm callback.
Reference: OSEK OS - ISO 17356-3 - 13.7.5
Parameters
[in] cbk the callback name
DeclareAlarm
#define DeclareAlarm (Alarm)
Declares an alarm.
This declaration is currently not mandatory because alarm identifiers are all declared within the code generated by RT-Druid.
Reference: OSEK OS - ISO 17356-3 - 13.7.2.1
Parameters
[in] Alarm The alarm to be declared.
Returns
void
INVALID_ALARM
#define INVALID_ALARM ((AlarmType)-1)
A constant representing an invalid alarm ID.
Typedef Documentation
AlarmBaseType
typedef struct TYPEDEF AlarmBaseType
This struct is returned by GetAlarmBase() filled with information about the counter to which an alarm is linked.
AlarmType
typedef OSEE_ALARM_ID_TYPE AlarmType
Type used to store an Alarm ID.
CounterType
typedef OSEE_COUNTER_TYPE CounterType
This type represents a counter.
TickRefType
typedef TickType TYPEDEF* OS_APPL_DATA TickRefType
This type is a pointer to a TickType, used as parameter of a primitive.
TickType
typedef OSEE_TICK_TYPE TickType
This type represents the value of ticks a counter can store.
Function Documentation
CancelAlarm()
StatusType OS_CODE CancelAlarm (AlarmType AlarmID)
The primitive cancels the alarm AlarmID. Allowed on task level and in ISR, but not in hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.7.3.5
Parameters
[in] AlarmID Alarm identifier.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_NOFUNC AlarmID not in use.
E_OS_ID (Extended) Reference AlarmID is invalid.
References AUTOMATIC, CancelAlarm(), OS_CODE, and VAR.
Referenced by CancelAlarm().
GetAlarm()
StatusType OS_CODE GetAlarm (AlarmType AlarmID, TickRefType Tick)
The system service GetAlarm() returns the relative value in ticks before the alarm AlarmID expires. If AlarmID is not in use, Tick has an undefined value. Allowed on task level, ISR, and in several hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.7.3.2
Parameters
[in] AlarmID Alarm identifier.
[out] Tick Relative value in ticks before the alarm expires.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_NOFUNC AlarmID is not used.
E_OS_ID (Extended) Reference AlarmID is invalid.
References AUTOMATIC, FUNC, GetAlarm(), OS_CODE, and VAR.
Referenced by GetAlarm().
GetAlarmBase()
StatusType OS_CODE GetAlarmBase (AlarmType AlarmID, AlarmBaseRefType Info)
Returns the alarm base characteristics. The return value Info is a structure in which the information of data type AlarmBaseType is stored.
Allowed on task level, ISR, and in several hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.7.3.1
Parameters
[in] AlarmID Alarm identifier.
[out] Info Reference to the structure containing the constants that define the alarm base.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ID (Extended) Reference AlarmID is invalid.
References AUTOMATIC, FUNC, GetAlarmBase(), OS_CODE, and VAR.
Referenced by GetAlarmBase().
GetCounterValue()
StatusType OS_CODE GetCounterValue (CounterType CounterID, TickRefType Value)
This service reads the current count value of a counter returning or the software ticks.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: AUTOSAR OS - SWS_Os_00383
Parameters
[in] CounterID The counter whose tick value should be read.
[out] Value The value read from the Counter
Returns
The function returns a StatusType.
E_OK No Error.
E_OS_ID (Extended) Reference CounterID is invalid.
References AUTOMATIC, FUNC, GetCounterValue(), OS_CODE, and VAR.
Referenced by GetCounterValue().
GetElapsedValue()
StatusType OS_CODE GetElapsedValue (CounterType CounterID, TickRefType Value, TickRefType ElapsedValue)
This service gets the number of ticks between the current tick value and a previously read tick value. If the timer already passed the Value value a second (or multiple) time, the result returned is wrong. The reason is that the service can not detect such a relative overflow.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: AUTOSAR OS - SWS_Os_00392
Parameters
[in] CounterID The Counter which tick value should be read.
[out] Value Contains the previously read tick value the counter.
[out] ElapsedValue Will contains the difference to the previous value.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ID (Extended) Reference CounterID is invalid.
E_OS_VALUE (Extended) The given Value is invalid.
References AUTOMATIC, FUNC, GetElapsedValue(), OS_CODE, and VAR.
Referenced by GetElapsedValue().
IncrementCounter()
StatusType OS_CODE IncrementCounter (CounterType CounterID)
This function receives a counter identifier as parameter, and it increments it by 1. This function is typically called inside an ISR type 2 or inside a task to notify that the trigger the counter is counting has happened.
The function also implements the notification of expired alarms, that is implemented, depending on the alarm configuration, as:
an alarm callback function;
a task activation;
an event mask set on an extended task.
The function is atomic, and a reschedule will happen at the end if the primitive is called at task level. If called at ISR level, the reschedule will happen at the end of the outermost nested IRQ.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: AUTOSAR OS SWS_Os_00301
Parameters
[in] CounterID The counter.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ID (Extended) CounterID is invalid or counter is implemented in hardware and can not be incremented by software.
References AUTOMATIC, IncrementCounter(), OS_CODE, and VAR.
Referenced by IncrementCounter().
SetAbsAlarm()
StatusType OS_CODE SetAbsAlarm (AlarmType AlarmID, TickType start, TickType cycle)
The primitive occupies the alarm AlarmID element. When start ticks are reached, the AlarmID notification is executed.
If the absolute value start is equal to the actual counter value, the alarm not expire immediately but will expire the next time the counter will reach the start value.
If cycle is unequal zero, the alarm element is logged on again immediately after expiry with the relative value cycle.
The alarm AlarmID shall not already be in use. To change values of alarms already in use the alarm shall be canceled first. If the alarm is already in use, this call will be ignored and the error E_OS_STATE is returned. Allowed on task level and in ISR, but not in hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.7.3.4
Parameters
[in] AlarmID Alarm identifier.
[in] start Absolute value in ticks representing the absolute offset of the first alarm expiration.
[in] cycle Cycle value in case of cyclic alarm. In case of single alarms, this parameter must be set to 0.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_STATE Alarm is already in use.
E_OS_ID (Extended) reference AlarmID is invalid.
E_OS_VALUE (Extended) Value of increment outside of the admissible limits, or value of cycle unequal to 0 and outside of the admissible counter limits.
References AUTOMATIC, FUNC, OS_CODE, SetAbsAlarm(), and VAR.
Referenced by SetAbsAlarm().
SetRelAlarm()
StatusType OS_CODE SetRelAlarm (AlarmType AlarmID, TickType increment, TickType cycle)
After increment ticks have elapsed, the AlarmID notification is executed.
If the relative value increment is very small, the alarm may expire, and the notification can be executed before the system service returns to the user. If cycle is unequal zero, the alarm element is logged on again immediately after expiry with the relative value cycle.
The alarm AlarmID must not already be in use. To change values of alarms already in use the alarm shall be canceled first.
If the alarm is already in use, this call will be ignored and the error E_OS_STATE is returned. Allowed on task level and in ISR, but not in hook routines.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.7.3.3
Parameters
[in] AlarmID Alarm identifier.
[in] increment Relative value in ticks representing the offset with respect to the current time of the first alarm expiration.
[in] cycle Cycle value in case of cyclic alarm. In case of single alarms, this parameter must be set to 0.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_STATE Alarm is already in use.
E_OS_ID (Extended) reference AlarmID is invalid.
E_OS_VALUE Value of increment equal to 0.
E_OS_VALUE (Extended) Value of increment outside of the admissible limits, or value of cycle unequal to 0 and outside of the admissible counter limits.
References AUTOMATIC, FUNC, OS_CODE, SetRelAlarm(), and VAR.
Referenced by SetRelAlarm().