Erika3 Manual: Resource Primitives
Resource Primitives
The Resource Primitives are related to shared resource handling in single cores.
Macros
#define INVALID_RESOURCE ((ResourceType)-1)
Invalid resource ID.
#define DeclareResource(Res)
Resource Declaration.
Typedefs
typedef OSEE_RESOURCE_ID_TYPE ResourceType
Type for Resource IDs.
typedef OSEE_SCHEDULETABLE_TYPE ScheduleTableType
Type for Schedule Tables.
Functions
StatusType OS_CODE GetResource (ResourceType ResID)
Locks a shared resource.
StatusType OS_CODE ReleaseResource (ResourceType ResID)
Releases a resource previously locked with GetResource.
Detailed Description
Resources are the term used by ERIKA3 to refer to binary semaphores used to implement shared critical sections.
Resources are implemented using the Immediate Priority Ceiling protocol.
A resource is locked using the primitive GetResource(), and unlocked using ReleaseResource().
A special resource named RES_SCHEDULER is also supported. The RES_SCHEDULER resource has a ceiling equal to the highest priority in the system. As a result, a task locking RES_SCHEDULER becomes non-preemptive. If needed, the RES_SCHEDULER resource have to be configured in the OIL configuration file.
On multiprocessor systems, Resources are divided in:
Local resources A Resource is local when all the tasks that uses it are assigned to the same processor. In this case you should use a Resource to implement the mutual exclusion.
Global resources A Resource is global when the tasks that uses it are assigned to different processors. In this case you should use a Spin Lock to implement the mutual exclusion.
A special kind of resources, called Internal Resources, are also supported by ERIKA3. Internal Resources are locked when the tasks enter the RUNNING state, and it is released when the task ends. Internal resources are used by optimization algorithms to limit the maximum stack space used by application tasks. Please note that Schedule() explicitly release any Internal Resource locked by the running task, thus limiting the possibility to reduce the overall stack in the system. Also WaitEvent() always release the internal resource of the task; however, this fact does not impact on stack usage because tasks using WaitEvent() must run on a private stack since WaitEvent() is a blocking primitive. Please also note that on Multicore systems, Internal Resources can only be local. Global Internal Resources are not supported.
ERIKA3 supports resource management at ISR level for a selected number of architectures. Please check on the ERIKA3 wiki whether the architecture you are currently using supports this feature. The implementation of this feature is implemented extending the OIL configuration to accept ISR priority as extra field in ISR Object definition. The ISR Priority field contains architecture independent values which are then mapped by RT-Druid to Task and Interrupt Controller priority values.
Macro Definition Documentation
DeclareResource
#define DeclareResource (Res)
Declares a resource used by Tasks.
This declaration is currently not mandatory because resource identifiers are all declared within the code generated by RT-Druid.
Reference: OSEK OS - ISO 17356-3 - 13.5.2.1
Parameters
[in] Res The resource to be declared.
Returns
void
INVALID_RESOURCE
#define INVALID_RESOURCE ((ResourceType)-1)
A constant representing an invalid Resource.
Typedef Documentation
ResourceType
typedef OSEE_RESOURCE_ID_TYPE ResourceType
Type used to store a Resource ID.
ScheduleTableType
typedef OSEE_SCHEDULETABLE_TYPE ScheduleTableType
Type used to store a Schedule Table.
Function Documentation
GetResource()
StatusType OS_CODE GetResource (ResourceType ResID)
This primitive can be used to implement a critical section guarded by Resource ResID. The critical section will end with the call to ReleaseResource().
Nesting between critical sections guarded by different resources is allowed.
Calls to TerminateTask(), ChainTask(), Schedule(), and WaitEvent() are not allowed inside the critical section.
Resources may be called on ISR level as well (see ISO17356-3 8.7).
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.5.3.1
Parameters
[in] ResID The resource to lock.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_ID (Extended) Resource ResID is invalid.
E_OS_ACCESS (Extended) Attempt to get a resource which is already occupied by any task or ISR, or the statically assigned priority of the calling task or interrupt routine is higher than the calculated ceiling priority.
References AUTOMATIC, FUNC, GetResource(), OS_CODE, and VAR.
Referenced by GetResource().
ReleaseResource()
StatusType OS_CODE ReleaseResource (ResourceType ResID)
ReleaseResource() is used to release a resource locked using GetResource(), closing a critical section.
For information on nested critical sections, see GetResource(). The service may be called from an ISR and from task level.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.5.3.2
Parameters
[in] ResID The resource to lock.
Returns
The function returns a StatusType.
E_OK No error
E_OS_ID (Extended) ResID is an invalid identifier
E_OS_NOFUNC (Extended) Attempt to release a resource which is not occupied by any task or ISR, or another resource shall be released before.
E_OS_ACCESS (Extended) Attempt to release a resource which has a lower ceiling priority than the statically assigned priority of the calling task or interrupt routine.
References AUTOMATIC, OS_CODE, ReleaseResource(), and VAR.
Referenced by ReleaseResource().