Erika3 Manual: Task Primitives
Task Primitives
The Task Primitives are related to the start and stop of Tasks.
Macros
#define INVALID_TASK ((TaskType)-1)
This is the invalid task value.
#define OSEE_ISR2_PRIO_BIT ((TaskPrio)1U << ((sizeof(TaskPrio)*((size_t)CHAR_BIT)) - ((size_t)1U)))
Most significant bit of a priority.
#define OSEE_ISR_ALL_PRIO ((TaskPrio)-1)
Bit mask for all priority bits.
#define DeclareTask(TaskToBeDeclared)
Task Declaration.
#define TASK(TaskToBeDefined)
Task Definition.
Typedefs
typedef OSEE_TASK_ID_TYPE TaskType
Type used for Task IDs.
typedef TaskType TYPEDEF *OS_APPL_DATA TaskRefType
This is a pointer to a TaskType.
typedef OSEE_TASK_PRIO_TYPE TaskPrio
Type storing task priorities.
typedef OsEE_task_status TYPEDEF TaskStateType
Task state type.
Functions
StatusType OS_CODE ActivateTask (TaskType TaskID)
This primitive activates a task TaskID.
StatusType OS_CODE ChainTask (TaskType TaskID)
Terminates the calling task, and atomically activates the TaskID passed as parameter.
StatusType OS_CODE TerminateTask (void)
Terminates the calling task.
StatusType OS_CODE GetTaskID (TaskRefType TaskID)
Returns the Task ID of the running task.
StatusType OS_CODE GetTaskState (TaskType TaskID, TaskStateRefType State)
This primitive returns the state of a given task.
StatusType OS_CODE Schedule (void)
A rescheduling point typically used in non-preemptive tasks.
Detailed Description
Independently of the task type all kernel primitives that may cause rescheduling may be called in any Tasks' sub-functions.
Tasks are activated using the primitives ActivateTask() or ChainTask(). Activating a task means that the activated task, may be selected for scheduling, and may execute one Task Instance. A task activation while a task is already waiting its execution or while being the running task has an effect that depends on how many pending activations the particular Conformance Class can store. BCC1 and ECC1 does not store pending activations, whereas BCC2 and ECC2 can store pending activations if the task has been properly configured in the OIL Configuration file.
Tasks must end with a call either to TerminateTask() or ChainTask(). Terminating a task without one of these two primitives leads to indefinite results.
Macro Definition Documentation
DeclareTask
#define DeclareTask (TaskToBeDeclared)
Value:
        extern FUNC(void, OS_CODE) Func##TaskToBeDeclared ( void )
Declares a task. It is equivalent of an externa declaration of a task function defined with the TASK() macro.
This declaration is currently not mandatory because task identifiers are all declared within the code generated by RT-Druid.
Reference: OSEK OS - ISO 17356-3 - 13.3.2.1
Parameters
[in] TaskToBeDeclared The task to be declared.
Returns
void
INVALID_TASK
#define INVALID_TASK ((TaskType)-1)
This is the invalid task value. No task can have this task ID. GetTaskID() executed in the background task (or idle hook) always provides INVALID_TASK.
OSEE_ISR2_PRIO_BIT
#define OSEE_ISR2_PRIO_BIT ((TaskPrio)1U << ((sizeof(TaskPrio)*((size_t)CHAR_BIT)) - ((size_t)1U)))
This is the most significant bit of a priority Note that a priority that has this bit to 1 is a "virtual priority" of an ISR2.
OSEE_ISR_ALL_PRIO
#define OSEE_ISR_ALL_PRIO ((TaskPrio)-1)
Bit mask for all priority bits.
TASK
#define TASK (TaskToBeDefined)
Value:
        FUNC(void, OS_CODE) Func##TaskToBeDefined ( void )
This macro is used when defining the body of a task.
Reference: OSEK OS - ISO 17356-3 - 13.3.5
Parameters
[in] TaskToBeDefined This is the task keyword used also in the OIL file.
Typedef Documentation
TaskPrio
typedef OSEE_TASK_PRIO_TYPE TaskPrio
This type is used to store the priority of both Tasks and ISR2s (please remember that ISR2 are treated like tasks inside ERIKA3).
TaskPrio is an integer number (usually n bits=8).
Higher values for higher priorities.
The same variable maps two types of priorities, in two different value ranges:
The task priority
The ISR2 ''virtual'' priority.
The ISR2 virtual priority maps the interrupt controller prioriries on top of the Task priorities. This is done by allocating the two kind of priorities into two non-overlapping ranges.
Choosen the dimension 'n' in bit of the type, the priority space is partitioned in the following way:
0 Idle (Task) Priority,
1 .. 2^(n-1) - 1 Tasks priorities. (value for n=8, 1..127)
2^(n-1) .. 2^n-2 ISR2 virtual priorities (typically the hardware priority range is smaller than the size of this range) (value for n=8, 128..254)
2^n - 1 Special value used to not reenable interrupts (used for internal interrupts when we want prevent preemption, like for system timer or for Scheduling Inter Core Interrupts). (value for n=8, 255)
ISR2 virtual priorities are mapped to hardware priorities by a HAL porting function in the following way:
Virtual priority 2^(n-1) == lowest_hardware priority Virtual priority 2^(n-1) + 1 == second_lowest_harware_priority ... and so on.
TaskRefType
typedef TaskType TYPEDEF* OS_APPL_DATA TaskRefType
This type is a pointer to Task IDs, used as parameter of a primitive.
TaskStateType
typedef OsEE_task_status TYPEDEF TaskStateType
This is the TaskState type, which is used to store the Task states. TaskState is returned also by GetTaskState(), with one of the following values: SUSPENDED, READY, RUNNING, WAITING. The complete list of states are defined in the values of OsEE_task_status.
TaskType
typedef OSEE_TASK_ID_TYPE TaskType
Type used for Task IDs. Typically the size of a word on the microcontroller. It is a positive number (except the invalid task which is -1). The Task IDs are consistent and do not change in case of multicore configurations.
Function Documentation
ActivateTask()
StatusType OS_CODE ActivateTask (TaskType TaskID)
This primitive activates a task TaskID, putting it in the READY state, or in the RUNNING state if the scheduler finds that the activated task should become the running task.
Once activated, the task will run for an instance, starting from its first instruction. For the BCC2 and ECC2 Conformance classes, pending activations can be stored if the task has been configured with a number of activations greater than 1 within the OIL configuration file.
The function can be called from the Background task (typically, the main() function).
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.3.3.1
Parameters
[in] TaskID Task to be activated.
Returns
The function returns a StatusType
E_OK: No error.
E_OS_LIMIT: Too many pending activations of TaskID.
E_OS_ID: (Extended) TaskID is invalid.
References ActivateTask(), AUTOMATIC, FUNC, OS_CODE, and VAR.
Referenced by ActivateTask().
ChainTask()
StatusType OS_CODE ChainTask (TaskType TaskID)
This primitive is similar to TerminateTask, with the differences listed below.
After the calling task is terminated, TaskID is activated again.
If TaskID is the calling task ID, then the calling task is terminated, the Internal Resource is unlocked, and then the calling task is put again in the ready queue to be scheduled. The Internal Resource will be locked again when the task will be again selected for scheduling.
When called successfully, ChainTask does not return to the caller. In case of error the primitive returns, and the returned error value can be evaluated by the application.
When an extended task is transferred from suspended state into ready state all its events are cleared.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.3.3.3
Parameters
[in] TaskID The task to activate
Returns
The function returns a StatusType
No return: If the call is successful.
E_OS_LIMIT: Too many task activations of TaskID. The Task activation in this case is ignored.
E_OS_ID: (Extended) Task TaskID is invalid.
E_OS_RESOURCE: (Extended) Calling task still occupies resources.
E_OS_CALLEVEL: (Extended) Call at interrupt level.
References AUTOMATIC, ChainTask(), FUNC, OS_CODE, and VAR.
Referenced by ChainTask().
GetTaskID()
StatusType OS_CODE GetTaskID (TaskRefType TaskID)
The function returns the Task ID of the running task. If no task is running, INVALID_TASK is returned.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.3.3.5
Parameters
[out] TaskID The Task ID of the running task
Returns
The function always returns a StatusType of value E_OK.
References AUTOMATIC, FUNC, GetTaskID(), OS_CODE, and VAR.
Referenced by GetTaskID().
GetTaskState()
StatusType OS_CODE GetTaskState (TaskType TaskID, TaskStateRefType State)
This primitive returns the state of a given task. Possible states are listed in the definition of the TaskStateType.
If the task TaskID supports pending activation, and the task has been activated more than once, the results refer to the state of its oldest activation.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.3.3.6
Parameters
[in] TaskID The task for which we want to read the state.
[out] State The task state of TaskID.
Returns
The function returns a StatusType.
E_OK: (Extended) No error.
E_OS_ID: (Extended) Task TaskID is invalid.
References AUTOMATIC, FUNC, GetTaskState(), OS_CODE, and VAR.
Referenced by GetTaskState().
Schedule()
StatusType OS_CODE Schedule (void)
This primitive can be used as a rescheduling point for tasks that have Internal Resources and for non preemptive tasks (Non preemptive tasks can be seen as tasks with an Internal Resource with the highest priority ceiling available assigned.).
When this primitive is called, the task releases its Internal Resource, and checks if there are higher priority tasks that have to preempt (In that case, a preemption is implemented). When the primitive returns, the task will reacquire its internal resource.
The primitive does nothing if the calling task has no internal resource assigned.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.3.3.4
Returns
The function returns a StatusType.
E_OK: No error.
E_OS_CALLEVEL: (Extended) The primitive was called at interrupt level.
E_OS_RESOURCE: (Extended) The calling task occupies resources.
References OS_CODE, and Schedule().
Referenced by Schedule().
TerminateTask()
StatusType OS_CODE TerminateTask (void)
This primitive terminates the calling task. The function can be called from any function nesting: the stack space used by the task is also freed. The calling task should not have any Resource locked when this primitive is called (apart an Internal Resource that is automatically released with this call).
After the call, the calling task is set in the SUSPENDED state, and it can be reactivated again using ActivateTask, ChainTask, or using Alarm notifications.
All the tasks must terminate with a call to TerminateTask or ChainTask. If not present, TerminateTask will be called automatically.
With Standard Status, the primitive never returns. With Extended Status, the primitive may return in case of errors.
Conformance Classes: BCC1, BCC2, ECC1, ECC2
Reference: OSEK OS - ISO 17356-3 - 13.3.3.2
Returns
The function returns a StatusType
No return: If the call is successful.
E_OS_RESOURCE: (Extended) The task still occupies resources.
E_OS_CALLEVEL: (Extended) The function was called at interrupt level.
References FUNC, OS_CODE, and TerminateTask().
Referenced by TerminateTask().