Erika3 Manual: Counting Semaphores
Counting Semaphores
This section describes in detail the primitives provided by ERIKA3 to support counting semaphores as a way to implement mutual exclusion and synchronization between tasks.
Typedefs
typedef struct OsEE_sem_tag TYPEDEF *OS_APPL_DATA SemRefType
Pointer to a Semaphore data structure.
typedef OSEE_COUNT_TYPE CountType
Type for the semaphore counter.
Functions
StatusType OS_CODE WaitSem (SemRefType Sem)
Semaphore blocking wait.
StatusType OS_CODE PostSem (SemRefType Sem)
Post on a semaphore.
Detailed Description
Counting semaphores are an RTOS abstractions of an integer counter coupled with a blocking queue. Basically two main operations are possible on a semaphore, which are waiting on a semaphore, which results in decrementing the counter if the counter has a value greater than 0, or blocking the running task if the counter is 0, and posting on a semaphore, which results in a counter increment if there are no task blocked, or in the unblock of a blocked task otherwise.
ERIKA3 counting semaphores exports a simple interface which covers the basic functionalities of a semaphore, like:
Initializing a semaphore (InitSem());
Waiting on a semaphore in a blocking (WaitSem()) or non-blocking way (TryWaitSem());
Posting on a semaphore (PostSem());
Getting the value of a semaphore (GetValueSem()).
Since waiting on a semaphore may result in blocking the running task, the WaitSem() primitive should be called only if the calling task has a separate stack allocated to it. For this reason, the WaitSem() primitive can only be called by extended tasks in conformance classes ECC1 and ECC2. Semaphores are available as non blocking in conformance classes BCC1 and BCC2.
Semaphores can be allocated statically as a global variable, which allow to bypass the call to InitSem() .
Semaphores definition are not listed in the OIL file; semaphore primitives receive as a parameter a pointer to the semaphore descriptor.
The current semaphore implementation does not support multicore systems. That is, semaphores must be defined and used locally to the same CPU.
Counting semaphores do not avoid Priority Inversion problems. Please use Resources instead.
Counting semaphores are not part of the OSEK/VDX / AUTOSAR standards.
Function Documentation
PostSem()
StatusType OS_CODE PostSem (SemRefType Sem)
This primitive unblocks a task eventually blocked on the semaphore. If there are no tasks blocked on the semaphore, then the semaphore counter is incremented by one.
Conformance Classes: ECC1, ECC2
Parameters
[in] Sem The semaphore used by the primitive.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_VALUE The semaphore has not been incremented because its counter was equal to the semaphore maximum value EE_MAX_SEM_COUNTER.
References AUTOMATIC, PostSem(), and VAR.
Referenced by PostSem().
WaitSem()
StatusType OS_CODE WaitSem (SemRefType Sem)
If the semaphore counter is greater than 0, then the counter is decremented by one. If the counter has a value of 0, then the calling (running) task blocks.
This function can only be called by extended tasks in conformance classes ECC1 and ECC2.
Conformance Classes: ECC1, ECC2
Parameters
[in] Sem The semaphore used by the primitive.
Returns
The function returns a StatusType.
E_OK No error.
E_OS_CALLEVEL (Extended) The primitive was called at interrupt level.
E_OS_RESOURCE (Extended) The calling task occupies resources.
E_OS_ACCESS (Extended) The calling task is not an extended task.
References AUTOMATIC, FUNC, OS_CODE, VAR, and WaitSem().
Referenced by WaitSem().