name: Check Commits with Gitlint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Gitlint
        run: |
          python -m pip install gitlint

      - name: Run Gitlint
        run: gitlint
